
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _Addresses : SqlClientEntity
	{
		public _Addresses()
		{
			this.QuerySource = "Addresses";
			this.MappingName = "Addresses";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_AddressesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ID, ID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_AddressesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ID
			{
				get
				{
					return new SqlParameter("@ID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter UserID
			{
				get
				{
					return new SqlParameter("@UserID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter AddressName
			{
				get
				{
					return new SqlParameter("@AddressName", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter Area_id
			{
				get
				{
					return new SqlParameter("@Area_id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Latitude
			{
				get
				{
					return new SqlParameter("@Latitude", SqlDbType.Decimal, 0);
				}
			}
			
			public static SqlParameter Longitude
			{
				get
				{
					return new SqlParameter("@Longitude", SqlDbType.Decimal, 0);
				}
			}
			
			public static SqlParameter Mobile
			{
				get
				{
					return new SqlParameter("@Mobile", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Phone
			{
				get
				{
					return new SqlParameter("@Phone", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter AType
			{
				get
				{
					return new SqlParameter("@AType", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter StreetName
			{
				get
				{
					return new SqlParameter("@StreetName", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Build
			{
				get
				{
					return new SqlParameter("@Build", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter FloorNo
			{
				get
				{
					return new SqlParameter("@FloorNo", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter AdepartmentNo
			{
				get
				{
					return new SqlParameter("@AdepartmentNo", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Instructions
			{
				get
				{
					return new SqlParameter("@Instructions", SqlDbType.NVarChar, 1073741823);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ID = "ID";
            public const string UserID = "UserID";
            public const string AddressName = "AddressName";
            public const string Area_id = "Area_id";
            public const string Latitude = "Latitude";
            public const string Longitude = "Longitude";
            public const string Mobile = "Mobile";
            public const string Phone = "phone";
            public const string AType = "AType";
            public const string StreetName = "StreetName";
            public const string Build = "Build";
            public const string FloorNo = "FloorNo";
            public const string AdepartmentNo = "adepartmentNo";
            public const string Instructions = "Instructions";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _Addresses.PropertyNames.ID;
					ht[UserID] = _Addresses.PropertyNames.UserID;
					ht[AddressName] = _Addresses.PropertyNames.AddressName;
					ht[Area_id] = _Addresses.PropertyNames.Area_id;
					ht[Latitude] = _Addresses.PropertyNames.Latitude;
					ht[Longitude] = _Addresses.PropertyNames.Longitude;
					ht[Mobile] = _Addresses.PropertyNames.Mobile;
					ht[Phone] = _Addresses.PropertyNames.Phone;
					ht[AType] = _Addresses.PropertyNames.AType;
					ht[StreetName] = _Addresses.PropertyNames.StreetName;
					ht[Build] = _Addresses.PropertyNames.Build;
					ht[FloorNo] = _Addresses.PropertyNames.FloorNo;
					ht[AdepartmentNo] = _Addresses.PropertyNames.AdepartmentNo;
					ht[Instructions] = _Addresses.PropertyNames.Instructions;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ID = "ID";
            public const string UserID = "UserID";
            public const string AddressName = "AddressName";
            public const string Area_id = "Area_id";
            public const string Latitude = "Latitude";
            public const string Longitude = "Longitude";
            public const string Mobile = "Mobile";
            public const string Phone = "Phone";
            public const string AType = "AType";
            public const string StreetName = "StreetName";
            public const string Build = "Build";
            public const string FloorNo = "FloorNo";
            public const string AdepartmentNo = "AdepartmentNo";
            public const string Instructions = "Instructions";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _Addresses.ColumnNames.ID;
					ht[UserID] = _Addresses.ColumnNames.UserID;
					ht[AddressName] = _Addresses.ColumnNames.AddressName;
					ht[Area_id] = _Addresses.ColumnNames.Area_id;
					ht[Latitude] = _Addresses.ColumnNames.Latitude;
					ht[Longitude] = _Addresses.ColumnNames.Longitude;
					ht[Mobile] = _Addresses.ColumnNames.Mobile;
					ht[Phone] = _Addresses.ColumnNames.Phone;
					ht[AType] = _Addresses.ColumnNames.AType;
					ht[StreetName] = _Addresses.ColumnNames.StreetName;
					ht[Build] = _Addresses.ColumnNames.Build;
					ht[FloorNo] = _Addresses.ColumnNames.FloorNo;
					ht[AdepartmentNo] = _Addresses.ColumnNames.AdepartmentNo;
					ht[Instructions] = _Addresses.ColumnNames.Instructions;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ID = "s_ID";
            public const string UserID = "s_UserID";
            public const string AddressName = "s_AddressName";
            public const string Area_id = "s_Area_id";
            public const string Latitude = "s_Latitude";
            public const string Longitude = "s_Longitude";
            public const string Mobile = "s_Mobile";
            public const string Phone = "s_Phone";
            public const string AType = "s_AType";
            public const string StreetName = "s_StreetName";
            public const string Build = "s_Build";
            public const string FloorNo = "s_FloorNo";
            public const string AdepartmentNo = "s_AdepartmentNo";
            public const string Instructions = "s_Instructions";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ID
	    {
			get
	        {
				return base.Getint(ColumnNames.ID);
			}
			set
	        {
				base.Setint(ColumnNames.ID, value);
			}
		}

		public virtual int UserID
	    {
			get
	        {
				return base.Getint(ColumnNames.UserID);
			}
			set
	        {
				base.Setint(ColumnNames.UserID, value);
			}
		}

		public virtual string AddressName
	    {
			get
	        {
				return base.Getstring(ColumnNames.AddressName);
			}
			set
	        {
				base.Setstring(ColumnNames.AddressName, value);
			}
		}

		public virtual int Area_id
	    {
			get
	        {
				return base.Getint(ColumnNames.Area_id);
			}
			set
	        {
				base.Setint(ColumnNames.Area_id, value);
			}
		}

		public virtual decimal Latitude
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Latitude);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Latitude, value);
			}
		}

		public virtual decimal Longitude
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Longitude);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Longitude, value);
			}
		}

		public virtual string Mobile
	    {
			get
	        {
				return base.Getstring(ColumnNames.Mobile);
			}
			set
	        {
				base.Setstring(ColumnNames.Mobile, value);
			}
		}

		public virtual string Phone
	    {
			get
	        {
				return base.Getstring(ColumnNames.Phone);
			}
			set
	        {
				base.Setstring(ColumnNames.Phone, value);
			}
		}

		public virtual int AType
	    {
			get
	        {
				return base.Getint(ColumnNames.AType);
			}
			set
	        {
				base.Setint(ColumnNames.AType, value);
			}
		}

		public virtual string StreetName
	    {
			get
	        {
				return base.Getstring(ColumnNames.StreetName);
			}
			set
	        {
				base.Setstring(ColumnNames.StreetName, value);
			}
		}

		public virtual string Build
	    {
			get
	        {
				return base.Getstring(ColumnNames.Build);
			}
			set
	        {
				base.Setstring(ColumnNames.Build, value);
			}
		}

		public virtual string FloorNo
	    {
			get
	        {
				return base.Getstring(ColumnNames.FloorNo);
			}
			set
	        {
				base.Setstring(ColumnNames.FloorNo, value);
			}
		}

		public virtual string AdepartmentNo
	    {
			get
	        {
				return base.Getstring(ColumnNames.AdepartmentNo);
			}
			set
	        {
				base.Setstring(ColumnNames.AdepartmentNo, value);
			}
		}

		public virtual string Instructions
	    {
			get
	        {
				return base.Getstring(ColumnNames.Instructions);
			}
			set
	        {
				base.Setstring(ColumnNames.Instructions, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ID) ? string.Empty : base.GetintAsString(ColumnNames.ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ID);
				else
					this.ID = base.SetintAsString(ColumnNames.ID, value);
			}
		}

		public virtual string s_UserID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserID) ? string.Empty : base.GetintAsString(ColumnNames.UserID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserID);
				else
					this.UserID = base.SetintAsString(ColumnNames.UserID, value);
			}
		}

		public virtual string s_AddressName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AddressName) ? string.Empty : base.GetstringAsString(ColumnNames.AddressName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AddressName);
				else
					this.AddressName = base.SetstringAsString(ColumnNames.AddressName, value);
			}
		}

		public virtual string s_Area_id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Area_id) ? string.Empty : base.GetintAsString(ColumnNames.Area_id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Area_id);
				else
					this.Area_id = base.SetintAsString(ColumnNames.Area_id, value);
			}
		}

		public virtual string s_Latitude
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Latitude) ? string.Empty : base.GetdecimalAsString(ColumnNames.Latitude);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Latitude);
				else
					this.Latitude = base.SetdecimalAsString(ColumnNames.Latitude, value);
			}
		}

		public virtual string s_Longitude
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Longitude) ? string.Empty : base.GetdecimalAsString(ColumnNames.Longitude);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Longitude);
				else
					this.Longitude = base.SetdecimalAsString(ColumnNames.Longitude, value);
			}
		}

		public virtual string s_Mobile
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Mobile) ? string.Empty : base.GetstringAsString(ColumnNames.Mobile);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Mobile);
				else
					this.Mobile = base.SetstringAsString(ColumnNames.Mobile, value);
			}
		}

		public virtual string s_Phone
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Phone) ? string.Empty : base.GetstringAsString(ColumnNames.Phone);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Phone);
				else
					this.Phone = base.SetstringAsString(ColumnNames.Phone, value);
			}
		}

		public virtual string s_AType
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AType) ? string.Empty : base.GetintAsString(ColumnNames.AType);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AType);
				else
					this.AType = base.SetintAsString(ColumnNames.AType, value);
			}
		}

		public virtual string s_StreetName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.StreetName) ? string.Empty : base.GetstringAsString(ColumnNames.StreetName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.StreetName);
				else
					this.StreetName = base.SetstringAsString(ColumnNames.StreetName, value);
			}
		}

		public virtual string s_Build
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Build) ? string.Empty : base.GetstringAsString(ColumnNames.Build);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Build);
				else
					this.Build = base.SetstringAsString(ColumnNames.Build, value);
			}
		}

		public virtual string s_FloorNo
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.FloorNo) ? string.Empty : base.GetstringAsString(ColumnNames.FloorNo);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.FloorNo);
				else
					this.FloorNo = base.SetstringAsString(ColumnNames.FloorNo, value);
			}
		}

		public virtual string s_AdepartmentNo
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.AdepartmentNo) ? string.Empty : base.GetstringAsString(ColumnNames.AdepartmentNo);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.AdepartmentNo);
				else
					this.AdepartmentNo = base.SetstringAsString(ColumnNames.AdepartmentNo, value);
			}
		}

		public virtual string s_Instructions
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Instructions) ? string.Empty : base.GetstringAsString(ColumnNames.Instructions);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Instructions);
				else
					this.Instructions = base.SetstringAsString(ColumnNames.Instructions, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UserID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AddressName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AddressName, Parameters.AddressName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Area_id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Area_id, Parameters.Area_id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Latitude
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Latitude, Parameters.Latitude);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Longitude
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Longitude, Parameters.Longitude);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Mobile
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Mobile, Parameters.Mobile);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Phone
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Phone, Parameters.Phone);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AType
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AType, Parameters.AType);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter StreetName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.StreetName, Parameters.StreetName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Build
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Build, Parameters.Build);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter FloorNo
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.FloorNo, Parameters.FloorNo);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter AdepartmentNo
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.AdepartmentNo, Parameters.AdepartmentNo);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Instructions
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Instructions, Parameters.Instructions);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public WhereParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public WhereParameter AddressName
		    {
				get
		        {
					if(_AddressName_W == null)
	        	    {
						_AddressName_W = TearOff.AddressName;
					}
					return _AddressName_W;
				}
			}

			public WhereParameter Area_id
		    {
				get
		        {
					if(_Area_id_W == null)
	        	    {
						_Area_id_W = TearOff.Area_id;
					}
					return _Area_id_W;
				}
			}

			public WhereParameter Latitude
		    {
				get
		        {
					if(_Latitude_W == null)
	        	    {
						_Latitude_W = TearOff.Latitude;
					}
					return _Latitude_W;
				}
			}

			public WhereParameter Longitude
		    {
				get
		        {
					if(_Longitude_W == null)
	        	    {
						_Longitude_W = TearOff.Longitude;
					}
					return _Longitude_W;
				}
			}

			public WhereParameter Mobile
		    {
				get
		        {
					if(_Mobile_W == null)
	        	    {
						_Mobile_W = TearOff.Mobile;
					}
					return _Mobile_W;
				}
			}

			public WhereParameter Phone
		    {
				get
		        {
					if(_Phone_W == null)
	        	    {
						_Phone_W = TearOff.Phone;
					}
					return _Phone_W;
				}
			}

			public WhereParameter AType
		    {
				get
		        {
					if(_AType_W == null)
	        	    {
						_AType_W = TearOff.AType;
					}
					return _AType_W;
				}
			}

			public WhereParameter StreetName
		    {
				get
		        {
					if(_StreetName_W == null)
	        	    {
						_StreetName_W = TearOff.StreetName;
					}
					return _StreetName_W;
				}
			}

			public WhereParameter Build
		    {
				get
		        {
					if(_Build_W == null)
	        	    {
						_Build_W = TearOff.Build;
					}
					return _Build_W;
				}
			}

			public WhereParameter FloorNo
		    {
				get
		        {
					if(_FloorNo_W == null)
	        	    {
						_FloorNo_W = TearOff.FloorNo;
					}
					return _FloorNo_W;
				}
			}

			public WhereParameter AdepartmentNo
		    {
				get
		        {
					if(_AdepartmentNo_W == null)
	        	    {
						_AdepartmentNo_W = TearOff.AdepartmentNo;
					}
					return _AdepartmentNo_W;
				}
			}

			public WhereParameter Instructions
		    {
				get
		        {
					if(_Instructions_W == null)
	        	    {
						_Instructions_W = TearOff.Instructions;
					}
					return _Instructions_W;
				}
			}

			private WhereParameter _ID_W = null;
			private WhereParameter _UserID_W = null;
			private WhereParameter _AddressName_W = null;
			private WhereParameter _Area_id_W = null;
			private WhereParameter _Latitude_W = null;
			private WhereParameter _Longitude_W = null;
			private WhereParameter _Mobile_W = null;
			private WhereParameter _Phone_W = null;
			private WhereParameter _AType_W = null;
			private WhereParameter _StreetName_W = null;
			private WhereParameter _Build_W = null;
			private WhereParameter _FloorNo_W = null;
			private WhereParameter _AdepartmentNo_W = null;
			private WhereParameter _Instructions_W = null;

			public void WhereClauseReset()
			{
				_ID_W = null;
				_UserID_W = null;
				_AddressName_W = null;
				_Area_id_W = null;
				_Latitude_W = null;
				_Longitude_W = null;
				_Mobile_W = null;
				_Phone_W = null;
				_AType_W = null;
				_StreetName_W = null;
				_Build_W = null;
				_FloorNo_W = null;
				_AdepartmentNo_W = null;
				_Instructions_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UserID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AddressName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AddressName, Parameters.AddressName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Area_id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Area_id, Parameters.Area_id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Latitude
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Latitude, Parameters.Latitude);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Longitude
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Longitude, Parameters.Longitude);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Mobile
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Mobile, Parameters.Mobile);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Phone
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Phone, Parameters.Phone);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AType
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AType, Parameters.AType);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter StreetName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.StreetName, Parameters.StreetName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Build
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Build, Parameters.Build);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter FloorNo
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.FloorNo, Parameters.FloorNo);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter AdepartmentNo
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.AdepartmentNo, Parameters.AdepartmentNo);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Instructions
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Instructions, Parameters.Instructions);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public AggregateParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public AggregateParameter AddressName
		    {
				get
		        {
					if(_AddressName_W == null)
	        	    {
						_AddressName_W = TearOff.AddressName;
					}
					return _AddressName_W;
				}
			}

			public AggregateParameter Area_id
		    {
				get
		        {
					if(_Area_id_W == null)
	        	    {
						_Area_id_W = TearOff.Area_id;
					}
					return _Area_id_W;
				}
			}

			public AggregateParameter Latitude
		    {
				get
		        {
					if(_Latitude_W == null)
	        	    {
						_Latitude_W = TearOff.Latitude;
					}
					return _Latitude_W;
				}
			}

			public AggregateParameter Longitude
		    {
				get
		        {
					if(_Longitude_W == null)
	        	    {
						_Longitude_W = TearOff.Longitude;
					}
					return _Longitude_W;
				}
			}

			public AggregateParameter Mobile
		    {
				get
		        {
					if(_Mobile_W == null)
	        	    {
						_Mobile_W = TearOff.Mobile;
					}
					return _Mobile_W;
				}
			}

			public AggregateParameter Phone
		    {
				get
		        {
					if(_Phone_W == null)
	        	    {
						_Phone_W = TearOff.Phone;
					}
					return _Phone_W;
				}
			}

			public AggregateParameter AType
		    {
				get
		        {
					if(_AType_W == null)
	        	    {
						_AType_W = TearOff.AType;
					}
					return _AType_W;
				}
			}

			public AggregateParameter StreetName
		    {
				get
		        {
					if(_StreetName_W == null)
	        	    {
						_StreetName_W = TearOff.StreetName;
					}
					return _StreetName_W;
				}
			}

			public AggregateParameter Build
		    {
				get
		        {
					if(_Build_W == null)
	        	    {
						_Build_W = TearOff.Build;
					}
					return _Build_W;
				}
			}

			public AggregateParameter FloorNo
		    {
				get
		        {
					if(_FloorNo_W == null)
	        	    {
						_FloorNo_W = TearOff.FloorNo;
					}
					return _FloorNo_W;
				}
			}

			public AggregateParameter AdepartmentNo
		    {
				get
		        {
					if(_AdepartmentNo_W == null)
	        	    {
						_AdepartmentNo_W = TearOff.AdepartmentNo;
					}
					return _AdepartmentNo_W;
				}
			}

			public AggregateParameter Instructions
		    {
				get
		        {
					if(_Instructions_W == null)
	        	    {
						_Instructions_W = TearOff.Instructions;
					}
					return _Instructions_W;
				}
			}

			private AggregateParameter _ID_W = null;
			private AggregateParameter _UserID_W = null;
			private AggregateParameter _AddressName_W = null;
			private AggregateParameter _Area_id_W = null;
			private AggregateParameter _Latitude_W = null;
			private AggregateParameter _Longitude_W = null;
			private AggregateParameter _Mobile_W = null;
			private AggregateParameter _Phone_W = null;
			private AggregateParameter _AType_W = null;
			private AggregateParameter _StreetName_W = null;
			private AggregateParameter _Build_W = null;
			private AggregateParameter _FloorNo_W = null;
			private AggregateParameter _AdepartmentNo_W = null;
			private AggregateParameter _Instructions_W = null;

			public void AggregateClauseReset()
			{
				_ID_W = null;
				_UserID_W = null;
				_AddressName_W = null;
				_Area_id_W = null;
				_Latitude_W = null;
				_Longitude_W = null;
				_Mobile_W = null;
				_Phone_W = null;
				_AType_W = null;
				_StreetName_W = null;
				_Build_W = null;
				_FloorNo_W = null;
				_AdepartmentNo_W = null;
				_Instructions_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AddressesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AddressesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AddressesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserID);
			p.SourceColumn = ColumnNames.UserID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AddressName);
			p.SourceColumn = ColumnNames.AddressName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Area_id);
			p.SourceColumn = ColumnNames.Area_id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Latitude);
			p.SourceColumn = ColumnNames.Latitude;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Longitude);
			p.SourceColumn = ColumnNames.Longitude;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Mobile);
			p.SourceColumn = ColumnNames.Mobile;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Phone);
			p.SourceColumn = ColumnNames.Phone;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AType);
			p.SourceColumn = ColumnNames.AType;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.StreetName);
			p.SourceColumn = ColumnNames.StreetName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Build);
			p.SourceColumn = ColumnNames.Build;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.FloorNo);
			p.SourceColumn = ColumnNames.FloorNo;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.AdepartmentNo);
			p.SourceColumn = ColumnNames.AdepartmentNo;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Instructions);
			p.SourceColumn = ColumnNames.Instructions;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
