
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _AUsers : SqlClientEntity
	{
		public _AUsers()
		{
			this.QuerySource = "AUsers";
			this.MappingName = "AUsers";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_AUsersLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id, Id);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_AUsersLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Password
			{
				get
				{
					return new SqlParameter("@Password", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter Role_id
			{
				get
				{
					return new SqlParameter("@Role_id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Visible
			{
				get
				{
					return new SqlParameter("@Visible", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter DefaultPage
			{
				get
				{
					return new SqlParameter("@DefaultPage", SqlDbType.VarChar, 50);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string Name = "name";
            public const string Password = "Password";
            public const string Role_id = "Role_id";
            public const string Visible = "Visible";
            public const string DefaultPage = "DefaultPage";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _AUsers.PropertyNames.Id;
					ht[Name] = _AUsers.PropertyNames.Name;
					ht[Password] = _AUsers.PropertyNames.Password;
					ht[Role_id] = _AUsers.PropertyNames.Role_id;
					ht[Visible] = _AUsers.PropertyNames.Visible;
					ht[DefaultPage] = _AUsers.PropertyNames.DefaultPage;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Name = "Name";
            public const string Password = "Password";
            public const string Role_id = "Role_id";
            public const string Visible = "Visible";
            public const string DefaultPage = "DefaultPage";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _AUsers.ColumnNames.Id;
					ht[Name] = _AUsers.ColumnNames.Name;
					ht[Password] = _AUsers.ColumnNames.Password;
					ht[Role_id] = _AUsers.ColumnNames.Role_id;
					ht[Visible] = _AUsers.ColumnNames.Visible;
					ht[DefaultPage] = _AUsers.ColumnNames.DefaultPage;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Name = "s_Name";
            public const string Password = "s_Password";
            public const string Role_id = "s_Role_id";
            public const string Visible = "s_Visible";
            public const string DefaultPage = "s_DefaultPage";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string Password
	    {
			get
	        {
				return base.Getstring(ColumnNames.Password);
			}
			set
	        {
				base.Setstring(ColumnNames.Password, value);
			}
		}

		public virtual int Role_id
	    {
			get
	        {
				return base.Getint(ColumnNames.Role_id);
			}
			set
	        {
				base.Setint(ColumnNames.Role_id, value);
			}
		}

		public virtual bool Visible
	    {
			get
	        {
				return base.Getbool(ColumnNames.Visible);
			}
			set
	        {
				base.Setbool(ColumnNames.Visible, value);
			}
		}

		public virtual string DefaultPage
	    {
			get
	        {
				return base.Getstring(ColumnNames.DefaultPage);
			}
			set
	        {
				base.Setstring(ColumnNames.DefaultPage, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_Password
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Password) ? string.Empty : base.GetstringAsString(ColumnNames.Password);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Password);
				else
					this.Password = base.SetstringAsString(ColumnNames.Password, value);
			}
		}

		public virtual string s_Role_id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Role_id) ? string.Empty : base.GetintAsString(ColumnNames.Role_id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Role_id);
				else
					this.Role_id = base.SetintAsString(ColumnNames.Role_id, value);
			}
		}

		public virtual string s_Visible
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Visible) ? string.Empty : base.GetboolAsString(ColumnNames.Visible);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Visible);
				else
					this.Visible = base.SetboolAsString(ColumnNames.Visible, value);
			}
		}

		public virtual string s_DefaultPage
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DefaultPage) ? string.Empty : base.GetstringAsString(ColumnNames.DefaultPage);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DefaultPage);
				else
					this.DefaultPage = base.SetstringAsString(ColumnNames.DefaultPage, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Password
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Password, Parameters.Password);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Role_id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Role_id, Parameters.Role_id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Visible
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Visible, Parameters.Visible);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DefaultPage
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DefaultPage, Parameters.DefaultPage);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter Password
		    {
				get
		        {
					if(_Password_W == null)
	        	    {
						_Password_W = TearOff.Password;
					}
					return _Password_W;
				}
			}

			public WhereParameter Role_id
		    {
				get
		        {
					if(_Role_id_W == null)
	        	    {
						_Role_id_W = TearOff.Role_id;
					}
					return _Role_id_W;
				}
			}

			public WhereParameter Visible
		    {
				get
		        {
					if(_Visible_W == null)
	        	    {
						_Visible_W = TearOff.Visible;
					}
					return _Visible_W;
				}
			}

			public WhereParameter DefaultPage
		    {
				get
		        {
					if(_DefaultPage_W == null)
	        	    {
						_DefaultPage_W = TearOff.DefaultPage;
					}
					return _DefaultPage_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _Password_W = null;
			private WhereParameter _Role_id_W = null;
			private WhereParameter _Visible_W = null;
			private WhereParameter _DefaultPage_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_Password_W = null;
				_Role_id_W = null;
				_Visible_W = null;
				_DefaultPage_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Password
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Password, Parameters.Password);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Role_id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Role_id, Parameters.Role_id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Visible
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Visible, Parameters.Visible);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DefaultPage
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DefaultPage, Parameters.DefaultPage);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter Password
		    {
				get
		        {
					if(_Password_W == null)
	        	    {
						_Password_W = TearOff.Password;
					}
					return _Password_W;
				}
			}

			public AggregateParameter Role_id
		    {
				get
		        {
					if(_Role_id_W == null)
	        	    {
						_Role_id_W = TearOff.Role_id;
					}
					return _Role_id_W;
				}
			}

			public AggregateParameter Visible
		    {
				get
		        {
					if(_Visible_W == null)
	        	    {
						_Visible_W = TearOff.Visible;
					}
					return _Visible_W;
				}
			}

			public AggregateParameter DefaultPage
		    {
				get
		        {
					if(_DefaultPage_W == null)
	        	    {
						_DefaultPage_W = TearOff.DefaultPage;
					}
					return _DefaultPage_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _Password_W = null;
			private AggregateParameter _Role_id_W = null;
			private AggregateParameter _Visible_W = null;
			private AggregateParameter _DefaultPage_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_Password_W = null;
				_Role_id_W = null;
				_Visible_W = null;
				_DefaultPage_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AUsersInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AUsersUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_AUsersDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Password);
			p.SourceColumn = ColumnNames.Password;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Role_id);
			p.SourceColumn = ColumnNames.Role_id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Visible);
			p.SourceColumn = ColumnNames.Visible;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DefaultPage);
			p.SourceColumn = ColumnNames.DefaultPage;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
