
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _Categories : SqlClientEntity
	{
		public _Categories()
		{
			this.QuerySource = "Categories";
			this.MappingName = "Categories";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CategoriesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id, Id);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CategoriesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter NameEn
			{
				get
				{
					return new SqlParameter("@NameEn", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter NameRu
			{
				get
				{
					return new SqlParameter("@NameRu", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter DescrAr
			{
				get
				{
					return new SqlParameter("@DescrAr", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter DescrEn
			{
				get
				{
					return new SqlParameter("@DescrEn", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter DescrRu
			{
				get
				{
					return new SqlParameter("@DescrRu", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Corder
			{
				get
				{
					return new SqlParameter("@Corder", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter PhotoPath
			{
				get
				{
					return new SqlParameter("@PhotoPath", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter Active
			{
				get
				{
					return new SqlParameter("@Active", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string Name = "Name";
            public const string NameEn = "NameEn";
            public const string NameRu = "NameRu";
            public const string DescrAr = "DescrAr";
            public const string DescrEn = "DescrEn";
            public const string DescrRu = "DescrRu";
            public const string Corder = "Corder";
            public const string PhotoPath = "PhotoPath";
            public const string Active = "Active";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Categories.PropertyNames.Id;
					ht[Name] = _Categories.PropertyNames.Name;
					ht[NameEn] = _Categories.PropertyNames.NameEn;
					ht[NameRu] = _Categories.PropertyNames.NameRu;
					ht[DescrAr] = _Categories.PropertyNames.DescrAr;
					ht[DescrEn] = _Categories.PropertyNames.DescrEn;
					ht[DescrRu] = _Categories.PropertyNames.DescrRu;
					ht[Corder] = _Categories.PropertyNames.Corder;
					ht[PhotoPath] = _Categories.PropertyNames.PhotoPath;
					ht[Active] = _Categories.PropertyNames.Active;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Name = "Name";
            public const string NameEn = "NameEn";
            public const string NameRu = "NameRu";
            public const string DescrAr = "DescrAr";
            public const string DescrEn = "DescrEn";
            public const string DescrRu = "DescrRu";
            public const string Corder = "Corder";
            public const string PhotoPath = "PhotoPath";
            public const string Active = "Active";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Categories.ColumnNames.Id;
					ht[Name] = _Categories.ColumnNames.Name;
					ht[NameEn] = _Categories.ColumnNames.NameEn;
					ht[NameRu] = _Categories.ColumnNames.NameRu;
					ht[DescrAr] = _Categories.ColumnNames.DescrAr;
					ht[DescrEn] = _Categories.ColumnNames.DescrEn;
					ht[DescrRu] = _Categories.ColumnNames.DescrRu;
					ht[Corder] = _Categories.ColumnNames.Corder;
					ht[PhotoPath] = _Categories.ColumnNames.PhotoPath;
					ht[Active] = _Categories.ColumnNames.Active;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Name = "s_Name";
            public const string NameEn = "s_NameEn";
            public const string NameRu = "s_NameRu";
            public const string DescrAr = "s_DescrAr";
            public const string DescrEn = "s_DescrEn";
            public const string DescrRu = "s_DescrRu";
            public const string Corder = "s_Corder";
            public const string PhotoPath = "s_PhotoPath";
            public const string Active = "s_Active";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string NameEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameEn);
			}
			set
	        {
				base.Setstring(ColumnNames.NameEn, value);
			}
		}

		public virtual string NameRu
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameRu);
			}
			set
	        {
				base.Setstring(ColumnNames.NameRu, value);
			}
		}

		public virtual string DescrAr
	    {
			get
	        {
				return base.Getstring(ColumnNames.DescrAr);
			}
			set
	        {
				base.Setstring(ColumnNames.DescrAr, value);
			}
		}

		public virtual string DescrEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.DescrEn);
			}
			set
	        {
				base.Setstring(ColumnNames.DescrEn, value);
			}
		}

		public virtual string DescrRu
	    {
			get
	        {
				return base.Getstring(ColumnNames.DescrRu);
			}
			set
	        {
				base.Setstring(ColumnNames.DescrRu, value);
			}
		}

		public virtual int Corder
	    {
			get
	        {
				return base.Getint(ColumnNames.Corder);
			}
			set
	        {
				base.Setint(ColumnNames.Corder, value);
			}
		}

		public virtual string PhotoPath
	    {
			get
	        {
				return base.Getstring(ColumnNames.PhotoPath);
			}
			set
	        {
				base.Setstring(ColumnNames.PhotoPath, value);
			}
		}

		public virtual bool Active
	    {
			get
	        {
				return base.Getbool(ColumnNames.Active);
			}
			set
	        {
				base.Setbool(ColumnNames.Active, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_NameEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameEn) ? string.Empty : base.GetstringAsString(ColumnNames.NameEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameEn);
				else
					this.NameEn = base.SetstringAsString(ColumnNames.NameEn, value);
			}
		}

		public virtual string s_NameRu
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameRu) ? string.Empty : base.GetstringAsString(ColumnNames.NameRu);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameRu);
				else
					this.NameRu = base.SetstringAsString(ColumnNames.NameRu, value);
			}
		}

		public virtual string s_DescrAr
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DescrAr) ? string.Empty : base.GetstringAsString(ColumnNames.DescrAr);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DescrAr);
				else
					this.DescrAr = base.SetstringAsString(ColumnNames.DescrAr, value);
			}
		}

		public virtual string s_DescrEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DescrEn) ? string.Empty : base.GetstringAsString(ColumnNames.DescrEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DescrEn);
				else
					this.DescrEn = base.SetstringAsString(ColumnNames.DescrEn, value);
			}
		}

		public virtual string s_DescrRu
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DescrRu) ? string.Empty : base.GetstringAsString(ColumnNames.DescrRu);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DescrRu);
				else
					this.DescrRu = base.SetstringAsString(ColumnNames.DescrRu, value);
			}
		}

		public virtual string s_Corder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Corder) ? string.Empty : base.GetintAsString(ColumnNames.Corder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Corder);
				else
					this.Corder = base.SetintAsString(ColumnNames.Corder, value);
			}
		}

		public virtual string s_PhotoPath
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PhotoPath) ? string.Empty : base.GetstringAsString(ColumnNames.PhotoPath);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PhotoPath);
				else
					this.PhotoPath = base.SetstringAsString(ColumnNames.PhotoPath, value);
			}
		}

		public virtual string s_Active
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Active) ? string.Empty : base.GetboolAsString(ColumnNames.Active);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Active);
				else
					this.Active = base.SetboolAsString(ColumnNames.Active, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameRu
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameRu, Parameters.NameRu);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DescrAr
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DescrAr, Parameters.DescrAr);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DescrEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DescrEn, Parameters.DescrEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DescrRu
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DescrRu, Parameters.DescrRu);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Corder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Corder, Parameters.Corder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PhotoPath
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PhotoPath, Parameters.PhotoPath);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Active
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Active, Parameters.Active);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public WhereParameter NameRu
		    {
				get
		        {
					if(_NameRu_W == null)
	        	    {
						_NameRu_W = TearOff.NameRu;
					}
					return _NameRu_W;
				}
			}

			public WhereParameter DescrAr
		    {
				get
		        {
					if(_DescrAr_W == null)
	        	    {
						_DescrAr_W = TearOff.DescrAr;
					}
					return _DescrAr_W;
				}
			}

			public WhereParameter DescrEn
		    {
				get
		        {
					if(_DescrEn_W == null)
	        	    {
						_DescrEn_W = TearOff.DescrEn;
					}
					return _DescrEn_W;
				}
			}

			public WhereParameter DescrRu
		    {
				get
		        {
					if(_DescrRu_W == null)
	        	    {
						_DescrRu_W = TearOff.DescrRu;
					}
					return _DescrRu_W;
				}
			}

			public WhereParameter Corder
		    {
				get
		        {
					if(_Corder_W == null)
	        	    {
						_Corder_W = TearOff.Corder;
					}
					return _Corder_W;
				}
			}

			public WhereParameter PhotoPath
		    {
				get
		        {
					if(_PhotoPath_W == null)
	        	    {
						_PhotoPath_W = TearOff.PhotoPath;
					}
					return _PhotoPath_W;
				}
			}

			public WhereParameter Active
		    {
				get
		        {
					if(_Active_W == null)
	        	    {
						_Active_W = TearOff.Active;
					}
					return _Active_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _NameEn_W = null;
			private WhereParameter _NameRu_W = null;
			private WhereParameter _DescrAr_W = null;
			private WhereParameter _DescrEn_W = null;
			private WhereParameter _DescrRu_W = null;
			private WhereParameter _Corder_W = null;
			private WhereParameter _PhotoPath_W = null;
			private WhereParameter _Active_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_NameEn_W = null;
				_NameRu_W = null;
				_DescrAr_W = null;
				_DescrEn_W = null;
				_DescrRu_W = null;
				_Corder_W = null;
				_PhotoPath_W = null;
				_Active_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameRu
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameRu, Parameters.NameRu);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DescrAr
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DescrAr, Parameters.DescrAr);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DescrEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DescrEn, Parameters.DescrEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DescrRu
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DescrRu, Parameters.DescrRu);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Corder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Corder, Parameters.Corder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PhotoPath
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PhotoPath, Parameters.PhotoPath);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Active
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Active, Parameters.Active);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public AggregateParameter NameRu
		    {
				get
		        {
					if(_NameRu_W == null)
	        	    {
						_NameRu_W = TearOff.NameRu;
					}
					return _NameRu_W;
				}
			}

			public AggregateParameter DescrAr
		    {
				get
		        {
					if(_DescrAr_W == null)
	        	    {
						_DescrAr_W = TearOff.DescrAr;
					}
					return _DescrAr_W;
				}
			}

			public AggregateParameter DescrEn
		    {
				get
		        {
					if(_DescrEn_W == null)
	        	    {
						_DescrEn_W = TearOff.DescrEn;
					}
					return _DescrEn_W;
				}
			}

			public AggregateParameter DescrRu
		    {
				get
		        {
					if(_DescrRu_W == null)
	        	    {
						_DescrRu_W = TearOff.DescrRu;
					}
					return _DescrRu_W;
				}
			}

			public AggregateParameter Corder
		    {
				get
		        {
					if(_Corder_W == null)
	        	    {
						_Corder_W = TearOff.Corder;
					}
					return _Corder_W;
				}
			}

			public AggregateParameter PhotoPath
		    {
				get
		        {
					if(_PhotoPath_W == null)
	        	    {
						_PhotoPath_W = TearOff.PhotoPath;
					}
					return _PhotoPath_W;
				}
			}

			public AggregateParameter Active
		    {
				get
		        {
					if(_Active_W == null)
	        	    {
						_Active_W = TearOff.Active;
					}
					return _Active_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _NameEn_W = null;
			private AggregateParameter _NameRu_W = null;
			private AggregateParameter _DescrAr_W = null;
			private AggregateParameter _DescrEn_W = null;
			private AggregateParameter _DescrRu_W = null;
			private AggregateParameter _Corder_W = null;
			private AggregateParameter _PhotoPath_W = null;
			private AggregateParameter _Active_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_NameEn_W = null;
				_NameRu_W = null;
				_DescrAr_W = null;
				_DescrEn_W = null;
				_DescrRu_W = null;
				_Corder_W = null;
				_PhotoPath_W = null;
				_Active_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CategoriesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameEn);
			p.SourceColumn = ColumnNames.NameEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameRu);
			p.SourceColumn = ColumnNames.NameRu;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DescrAr);
			p.SourceColumn = ColumnNames.DescrAr;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DescrEn);
			p.SourceColumn = ColumnNames.DescrEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DescrRu);
			p.SourceColumn = ColumnNames.DescrRu;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Corder);
			p.SourceColumn = ColumnNames.Corder;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PhotoPath);
			p.SourceColumn = ColumnNames.PhotoPath;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Active);
			p.SourceColumn = ColumnNames.Active;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
