
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _Centers : SqlClientEntity
	{
		public _Centers()
		{
			this.QuerySource = "Centers";
			this.MappingName = "Centers";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CentersLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id, Id);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_CentersLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter Facebook
			{
				get
				{
					return new SqlParameter("@Facebook", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter Youyube
			{
				get
				{
					return new SqlParameter("@Youyube", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter Twitter
			{
				get
				{
					return new SqlParameter("@Twitter", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter GooglePlus
			{
				get
				{
					return new SqlParameter("@GooglePlus", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter LinkedIn
			{
				get
				{
					return new SqlParameter("@LinkedIn", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter Instgram
			{
				get
				{
					return new SqlParameter("@Instgram", SqlDbType.NVarChar, 250);
				}
			}
			
			public static SqlParameter Phone
			{
				get
				{
					return new SqlParameter("@Phone", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Mobile
			{
				get
				{
					return new SqlParameter("@Mobile", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Fax
			{
				get
				{
					return new SqlParameter("@Fax", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Mail
			{
				get
				{
					return new SqlParameter("@Mail", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter MailBox
			{
				get
				{
					return new SqlParameter("@MailBox", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Addresse
			{
				get
				{
					return new SqlParameter("@Addresse", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Map
			{
				get
				{
					return new SqlParameter("@Map", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter Pic
			{
				get
				{
					return new SqlParameter("@Pic", SqlDbType.NVarChar, 150);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string Name = "Name";
            public const string Facebook = "Facebook";
            public const string Youyube = "Youyube";
            public const string Twitter = "Twitter";
            public const string GooglePlus = "GooglePlus";
            public const string LinkedIn = "LinkedIn";
            public const string Instgram = "Instgram";
            public const string Phone = "Phone";
            public const string Mobile = "Mobile";
            public const string Fax = "Fax";
            public const string Mail = "Mail";
            public const string MailBox = "MailBox";
            public const string Addresse = "Addresse";
            public const string Map = "Map";
            public const string Pic = "Pic";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Centers.PropertyNames.Id;
					ht[Name] = _Centers.PropertyNames.Name;
					ht[Facebook] = _Centers.PropertyNames.Facebook;
					ht[Youyube] = _Centers.PropertyNames.Youyube;
					ht[Twitter] = _Centers.PropertyNames.Twitter;
					ht[GooglePlus] = _Centers.PropertyNames.GooglePlus;
					ht[LinkedIn] = _Centers.PropertyNames.LinkedIn;
					ht[Instgram] = _Centers.PropertyNames.Instgram;
					ht[Phone] = _Centers.PropertyNames.Phone;
					ht[Mobile] = _Centers.PropertyNames.Mobile;
					ht[Fax] = _Centers.PropertyNames.Fax;
					ht[Mail] = _Centers.PropertyNames.Mail;
					ht[MailBox] = _Centers.PropertyNames.MailBox;
					ht[Addresse] = _Centers.PropertyNames.Addresse;
					ht[Map] = _Centers.PropertyNames.Map;
					ht[Pic] = _Centers.PropertyNames.Pic;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Name = "Name";
            public const string Facebook = "Facebook";
            public const string Youyube = "Youyube";
            public const string Twitter = "Twitter";
            public const string GooglePlus = "GooglePlus";
            public const string LinkedIn = "LinkedIn";
            public const string Instgram = "Instgram";
            public const string Phone = "Phone";
            public const string Mobile = "Mobile";
            public const string Fax = "Fax";
            public const string Mail = "Mail";
            public const string MailBox = "MailBox";
            public const string Addresse = "Addresse";
            public const string Map = "Map";
            public const string Pic = "Pic";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Centers.ColumnNames.Id;
					ht[Name] = _Centers.ColumnNames.Name;
					ht[Facebook] = _Centers.ColumnNames.Facebook;
					ht[Youyube] = _Centers.ColumnNames.Youyube;
					ht[Twitter] = _Centers.ColumnNames.Twitter;
					ht[GooglePlus] = _Centers.ColumnNames.GooglePlus;
					ht[LinkedIn] = _Centers.ColumnNames.LinkedIn;
					ht[Instgram] = _Centers.ColumnNames.Instgram;
					ht[Phone] = _Centers.ColumnNames.Phone;
					ht[Mobile] = _Centers.ColumnNames.Mobile;
					ht[Fax] = _Centers.ColumnNames.Fax;
					ht[Mail] = _Centers.ColumnNames.Mail;
					ht[MailBox] = _Centers.ColumnNames.MailBox;
					ht[Addresse] = _Centers.ColumnNames.Addresse;
					ht[Map] = _Centers.ColumnNames.Map;
					ht[Pic] = _Centers.ColumnNames.Pic;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Name = "s_Name";
            public const string Facebook = "s_Facebook";
            public const string Youyube = "s_Youyube";
            public const string Twitter = "s_Twitter";
            public const string GooglePlus = "s_GooglePlus";
            public const string LinkedIn = "s_LinkedIn";
            public const string Instgram = "s_Instgram";
            public const string Phone = "s_Phone";
            public const string Mobile = "s_Mobile";
            public const string Fax = "s_Fax";
            public const string Mail = "s_Mail";
            public const string MailBox = "s_MailBox";
            public const string Addresse = "s_Addresse";
            public const string Map = "s_Map";
            public const string Pic = "s_Pic";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string Facebook
	    {
			get
	        {
				return base.Getstring(ColumnNames.Facebook);
			}
			set
	        {
				base.Setstring(ColumnNames.Facebook, value);
			}
		}

		public virtual string Youyube
	    {
			get
	        {
				return base.Getstring(ColumnNames.Youyube);
			}
			set
	        {
				base.Setstring(ColumnNames.Youyube, value);
			}
		}

		public virtual string Twitter
	    {
			get
	        {
				return base.Getstring(ColumnNames.Twitter);
			}
			set
	        {
				base.Setstring(ColumnNames.Twitter, value);
			}
		}

		public virtual string GooglePlus
	    {
			get
	        {
				return base.Getstring(ColumnNames.GooglePlus);
			}
			set
	        {
				base.Setstring(ColumnNames.GooglePlus, value);
			}
		}

		public virtual string LinkedIn
	    {
			get
	        {
				return base.Getstring(ColumnNames.LinkedIn);
			}
			set
	        {
				base.Setstring(ColumnNames.LinkedIn, value);
			}
		}

		public virtual string Instgram
	    {
			get
	        {
				return base.Getstring(ColumnNames.Instgram);
			}
			set
	        {
				base.Setstring(ColumnNames.Instgram, value);
			}
		}

		public virtual string Phone
	    {
			get
	        {
				return base.Getstring(ColumnNames.Phone);
			}
			set
	        {
				base.Setstring(ColumnNames.Phone, value);
			}
		}

		public virtual string Mobile
	    {
			get
	        {
				return base.Getstring(ColumnNames.Mobile);
			}
			set
	        {
				base.Setstring(ColumnNames.Mobile, value);
			}
		}

		public virtual string Fax
	    {
			get
	        {
				return base.Getstring(ColumnNames.Fax);
			}
			set
	        {
				base.Setstring(ColumnNames.Fax, value);
			}
		}

		public virtual string Mail
	    {
			get
	        {
				return base.Getstring(ColumnNames.Mail);
			}
			set
	        {
				base.Setstring(ColumnNames.Mail, value);
			}
		}

		public virtual string MailBox
	    {
			get
	        {
				return base.Getstring(ColumnNames.MailBox);
			}
			set
	        {
				base.Setstring(ColumnNames.MailBox, value);
			}
		}

		public virtual string Addresse
	    {
			get
	        {
				return base.Getstring(ColumnNames.Addresse);
			}
			set
	        {
				base.Setstring(ColumnNames.Addresse, value);
			}
		}

		public virtual string Map
	    {
			get
	        {
				return base.Getstring(ColumnNames.Map);
			}
			set
	        {
				base.Setstring(ColumnNames.Map, value);
			}
		}

		public virtual string Pic
	    {
			get
	        {
				return base.Getstring(ColumnNames.Pic);
			}
			set
	        {
				base.Setstring(ColumnNames.Pic, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_Facebook
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Facebook) ? string.Empty : base.GetstringAsString(ColumnNames.Facebook);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Facebook);
				else
					this.Facebook = base.SetstringAsString(ColumnNames.Facebook, value);
			}
		}

		public virtual string s_Youyube
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Youyube) ? string.Empty : base.GetstringAsString(ColumnNames.Youyube);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Youyube);
				else
					this.Youyube = base.SetstringAsString(ColumnNames.Youyube, value);
			}
		}

		public virtual string s_Twitter
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Twitter) ? string.Empty : base.GetstringAsString(ColumnNames.Twitter);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Twitter);
				else
					this.Twitter = base.SetstringAsString(ColumnNames.Twitter, value);
			}
		}

		public virtual string s_GooglePlus
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GooglePlus) ? string.Empty : base.GetstringAsString(ColumnNames.GooglePlus);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GooglePlus);
				else
					this.GooglePlus = base.SetstringAsString(ColumnNames.GooglePlus, value);
			}
		}

		public virtual string s_LinkedIn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.LinkedIn) ? string.Empty : base.GetstringAsString(ColumnNames.LinkedIn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.LinkedIn);
				else
					this.LinkedIn = base.SetstringAsString(ColumnNames.LinkedIn, value);
			}
		}

		public virtual string s_Instgram
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Instgram) ? string.Empty : base.GetstringAsString(ColumnNames.Instgram);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Instgram);
				else
					this.Instgram = base.SetstringAsString(ColumnNames.Instgram, value);
			}
		}

		public virtual string s_Phone
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Phone) ? string.Empty : base.GetstringAsString(ColumnNames.Phone);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Phone);
				else
					this.Phone = base.SetstringAsString(ColumnNames.Phone, value);
			}
		}

		public virtual string s_Mobile
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Mobile) ? string.Empty : base.GetstringAsString(ColumnNames.Mobile);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Mobile);
				else
					this.Mobile = base.SetstringAsString(ColumnNames.Mobile, value);
			}
		}

		public virtual string s_Fax
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Fax) ? string.Empty : base.GetstringAsString(ColumnNames.Fax);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Fax);
				else
					this.Fax = base.SetstringAsString(ColumnNames.Fax, value);
			}
		}

		public virtual string s_Mail
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Mail) ? string.Empty : base.GetstringAsString(ColumnNames.Mail);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Mail);
				else
					this.Mail = base.SetstringAsString(ColumnNames.Mail, value);
			}
		}

		public virtual string s_MailBox
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MailBox) ? string.Empty : base.GetstringAsString(ColumnNames.MailBox);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MailBox);
				else
					this.MailBox = base.SetstringAsString(ColumnNames.MailBox, value);
			}
		}

		public virtual string s_Addresse
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Addresse) ? string.Empty : base.GetstringAsString(ColumnNames.Addresse);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Addresse);
				else
					this.Addresse = base.SetstringAsString(ColumnNames.Addresse, value);
			}
		}

		public virtual string s_Map
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Map) ? string.Empty : base.GetstringAsString(ColumnNames.Map);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Map);
				else
					this.Map = base.SetstringAsString(ColumnNames.Map, value);
			}
		}

		public virtual string s_Pic
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Pic) ? string.Empty : base.GetstringAsString(ColumnNames.Pic);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Pic);
				else
					this.Pic = base.SetstringAsString(ColumnNames.Pic, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Facebook
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Facebook, Parameters.Facebook);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Youyube
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Youyube, Parameters.Youyube);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Twitter
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Twitter, Parameters.Twitter);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter GooglePlus
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GooglePlus, Parameters.GooglePlus);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter LinkedIn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.LinkedIn, Parameters.LinkedIn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Instgram
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Instgram, Parameters.Instgram);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Phone
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Phone, Parameters.Phone);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Mobile
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Mobile, Parameters.Mobile);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Fax
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Fax, Parameters.Fax);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Mail
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Mail, Parameters.Mail);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MailBox
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MailBox, Parameters.MailBox);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Addresse
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Addresse, Parameters.Addresse);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Map
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Map, Parameters.Map);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Pic
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Pic, Parameters.Pic);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter Facebook
		    {
				get
		        {
					if(_Facebook_W == null)
	        	    {
						_Facebook_W = TearOff.Facebook;
					}
					return _Facebook_W;
				}
			}

			public WhereParameter Youyube
		    {
				get
		        {
					if(_Youyube_W == null)
	        	    {
						_Youyube_W = TearOff.Youyube;
					}
					return _Youyube_W;
				}
			}

			public WhereParameter Twitter
		    {
				get
		        {
					if(_Twitter_W == null)
	        	    {
						_Twitter_W = TearOff.Twitter;
					}
					return _Twitter_W;
				}
			}

			public WhereParameter GooglePlus
		    {
				get
		        {
					if(_GooglePlus_W == null)
	        	    {
						_GooglePlus_W = TearOff.GooglePlus;
					}
					return _GooglePlus_W;
				}
			}

			public WhereParameter LinkedIn
		    {
				get
		        {
					if(_LinkedIn_W == null)
	        	    {
						_LinkedIn_W = TearOff.LinkedIn;
					}
					return _LinkedIn_W;
				}
			}

			public WhereParameter Instgram
		    {
				get
		        {
					if(_Instgram_W == null)
	        	    {
						_Instgram_W = TearOff.Instgram;
					}
					return _Instgram_W;
				}
			}

			public WhereParameter Phone
		    {
				get
		        {
					if(_Phone_W == null)
	        	    {
						_Phone_W = TearOff.Phone;
					}
					return _Phone_W;
				}
			}

			public WhereParameter Mobile
		    {
				get
		        {
					if(_Mobile_W == null)
	        	    {
						_Mobile_W = TearOff.Mobile;
					}
					return _Mobile_W;
				}
			}

			public WhereParameter Fax
		    {
				get
		        {
					if(_Fax_W == null)
	        	    {
						_Fax_W = TearOff.Fax;
					}
					return _Fax_W;
				}
			}

			public WhereParameter Mail
		    {
				get
		        {
					if(_Mail_W == null)
	        	    {
						_Mail_W = TearOff.Mail;
					}
					return _Mail_W;
				}
			}

			public WhereParameter MailBox
		    {
				get
		        {
					if(_MailBox_W == null)
	        	    {
						_MailBox_W = TearOff.MailBox;
					}
					return _MailBox_W;
				}
			}

			public WhereParameter Addresse
		    {
				get
		        {
					if(_Addresse_W == null)
	        	    {
						_Addresse_W = TearOff.Addresse;
					}
					return _Addresse_W;
				}
			}

			public WhereParameter Map
		    {
				get
		        {
					if(_Map_W == null)
	        	    {
						_Map_W = TearOff.Map;
					}
					return _Map_W;
				}
			}

			public WhereParameter Pic
		    {
				get
		        {
					if(_Pic_W == null)
	        	    {
						_Pic_W = TearOff.Pic;
					}
					return _Pic_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _Facebook_W = null;
			private WhereParameter _Youyube_W = null;
			private WhereParameter _Twitter_W = null;
			private WhereParameter _GooglePlus_W = null;
			private WhereParameter _LinkedIn_W = null;
			private WhereParameter _Instgram_W = null;
			private WhereParameter _Phone_W = null;
			private WhereParameter _Mobile_W = null;
			private WhereParameter _Fax_W = null;
			private WhereParameter _Mail_W = null;
			private WhereParameter _MailBox_W = null;
			private WhereParameter _Addresse_W = null;
			private WhereParameter _Map_W = null;
			private WhereParameter _Pic_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_Facebook_W = null;
				_Youyube_W = null;
				_Twitter_W = null;
				_GooglePlus_W = null;
				_LinkedIn_W = null;
				_Instgram_W = null;
				_Phone_W = null;
				_Mobile_W = null;
				_Fax_W = null;
				_Mail_W = null;
				_MailBox_W = null;
				_Addresse_W = null;
				_Map_W = null;
				_Pic_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Facebook
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Facebook, Parameters.Facebook);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Youyube
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Youyube, Parameters.Youyube);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Twitter
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Twitter, Parameters.Twitter);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter GooglePlus
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GooglePlus, Parameters.GooglePlus);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter LinkedIn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.LinkedIn, Parameters.LinkedIn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Instgram
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Instgram, Parameters.Instgram);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Phone
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Phone, Parameters.Phone);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Mobile
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Mobile, Parameters.Mobile);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Fax
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Fax, Parameters.Fax);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Mail
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Mail, Parameters.Mail);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MailBox
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MailBox, Parameters.MailBox);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Addresse
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Addresse, Parameters.Addresse);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Map
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Map, Parameters.Map);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Pic
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Pic, Parameters.Pic);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter Facebook
		    {
				get
		        {
					if(_Facebook_W == null)
	        	    {
						_Facebook_W = TearOff.Facebook;
					}
					return _Facebook_W;
				}
			}

			public AggregateParameter Youyube
		    {
				get
		        {
					if(_Youyube_W == null)
	        	    {
						_Youyube_W = TearOff.Youyube;
					}
					return _Youyube_W;
				}
			}

			public AggregateParameter Twitter
		    {
				get
		        {
					if(_Twitter_W == null)
	        	    {
						_Twitter_W = TearOff.Twitter;
					}
					return _Twitter_W;
				}
			}

			public AggregateParameter GooglePlus
		    {
				get
		        {
					if(_GooglePlus_W == null)
	        	    {
						_GooglePlus_W = TearOff.GooglePlus;
					}
					return _GooglePlus_W;
				}
			}

			public AggregateParameter LinkedIn
		    {
				get
		        {
					if(_LinkedIn_W == null)
	        	    {
						_LinkedIn_W = TearOff.LinkedIn;
					}
					return _LinkedIn_W;
				}
			}

			public AggregateParameter Instgram
		    {
				get
		        {
					if(_Instgram_W == null)
	        	    {
						_Instgram_W = TearOff.Instgram;
					}
					return _Instgram_W;
				}
			}

			public AggregateParameter Phone
		    {
				get
		        {
					if(_Phone_W == null)
	        	    {
						_Phone_W = TearOff.Phone;
					}
					return _Phone_W;
				}
			}

			public AggregateParameter Mobile
		    {
				get
		        {
					if(_Mobile_W == null)
	        	    {
						_Mobile_W = TearOff.Mobile;
					}
					return _Mobile_W;
				}
			}

			public AggregateParameter Fax
		    {
				get
		        {
					if(_Fax_W == null)
	        	    {
						_Fax_W = TearOff.Fax;
					}
					return _Fax_W;
				}
			}

			public AggregateParameter Mail
		    {
				get
		        {
					if(_Mail_W == null)
	        	    {
						_Mail_W = TearOff.Mail;
					}
					return _Mail_W;
				}
			}

			public AggregateParameter MailBox
		    {
				get
		        {
					if(_MailBox_W == null)
	        	    {
						_MailBox_W = TearOff.MailBox;
					}
					return _MailBox_W;
				}
			}

			public AggregateParameter Addresse
		    {
				get
		        {
					if(_Addresse_W == null)
	        	    {
						_Addresse_W = TearOff.Addresse;
					}
					return _Addresse_W;
				}
			}

			public AggregateParameter Map
		    {
				get
		        {
					if(_Map_W == null)
	        	    {
						_Map_W = TearOff.Map;
					}
					return _Map_W;
				}
			}

			public AggregateParameter Pic
		    {
				get
		        {
					if(_Pic_W == null)
	        	    {
						_Pic_W = TearOff.Pic;
					}
					return _Pic_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _Facebook_W = null;
			private AggregateParameter _Youyube_W = null;
			private AggregateParameter _Twitter_W = null;
			private AggregateParameter _GooglePlus_W = null;
			private AggregateParameter _LinkedIn_W = null;
			private AggregateParameter _Instgram_W = null;
			private AggregateParameter _Phone_W = null;
			private AggregateParameter _Mobile_W = null;
			private AggregateParameter _Fax_W = null;
			private AggregateParameter _Mail_W = null;
			private AggregateParameter _MailBox_W = null;
			private AggregateParameter _Addresse_W = null;
			private AggregateParameter _Map_W = null;
			private AggregateParameter _Pic_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_Facebook_W = null;
				_Youyube_W = null;
				_Twitter_W = null;
				_GooglePlus_W = null;
				_LinkedIn_W = null;
				_Instgram_W = null;
				_Phone_W = null;
				_Mobile_W = null;
				_Fax_W = null;
				_Mail_W = null;
				_MailBox_W = null;
				_Addresse_W = null;
				_Map_W = null;
				_Pic_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CentersInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CentersUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_CentersDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Facebook);
			p.SourceColumn = ColumnNames.Facebook;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Youyube);
			p.SourceColumn = ColumnNames.Youyube;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Twitter);
			p.SourceColumn = ColumnNames.Twitter;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.GooglePlus);
			p.SourceColumn = ColumnNames.GooglePlus;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.LinkedIn);
			p.SourceColumn = ColumnNames.LinkedIn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Instgram);
			p.SourceColumn = ColumnNames.Instgram;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Phone);
			p.SourceColumn = ColumnNames.Phone;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Mobile);
			p.SourceColumn = ColumnNames.Mobile;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Fax);
			p.SourceColumn = ColumnNames.Fax;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Mail);
			p.SourceColumn = ColumnNames.Mail;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MailBox);
			p.SourceColumn = ColumnNames.MailBox;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Addresse);
			p.SourceColumn = ColumnNames.Addresse;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Map);
			p.SourceColumn = ColumnNames.Map;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Pic);
			p.SourceColumn = ColumnNames.Pic;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
