
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _MenuItems : SqlClientEntity
	{
		public _MenuItems()
		{
			this.QuerySource = "MenuItems";
			this.MappingName = "MenuItems";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_MenuItemsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id, Id);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_MenuItemsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter MenuID
			{
				get
				{
					return new SqlParameter("@MenuID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter PlaceID
			{
				get
				{
					return new SqlParameter("@PlaceID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter NameEn
			{
				get
				{
					return new SqlParameter("@NameEn", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter NameRu
			{
				get
				{
					return new SqlParameter("@NameRu", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Description
			{
				get
				{
					return new SqlParameter("@Description", SqlDbType.NVarChar, 255);
				}
			}
			
			public static SqlParameter DescriptionEn
			{
				get
				{
					return new SqlParameter("@DescriptionEn", SqlDbType.NVarChar, 255);
				}
			}
			
			public static SqlParameter DescriptionRu
			{
				get
				{
					return new SqlParameter("@DescriptionRu", SqlDbType.NVarChar, 255);
				}
			}
			
			public static SqlParameter Price
			{
				get
				{
					return new SqlParameter("@Price", SqlDbType.Decimal, 0);
				}
			}
			
			public static SqlParameter DiscountValue
			{
				get
				{
					return new SqlParameter("@DiscountValue", SqlDbType.Decimal, 0);
				}
			}
			
			public static SqlParameter PhotoUrl
			{
				get
				{
					return new SqlParameter("@PhotoUrl", SqlDbType.NVarChar, 255);
				}
			}
			
			public static SqlParameter IsAvailable
			{
				get
				{
					return new SqlParameter("@IsAvailable", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter CreatedAt
			{
				get
				{
					return new SqlParameter("@CreatedAt", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string MenuID = "MenuID";
            public const string PlaceID = "PlaceID";
            public const string Name = "Name";
            public const string NameEn = "NameEn";
            public const string NameRu = "NameRu";
            public const string Description = "Description";
            public const string DescriptionEn = "DescriptionEn";
            public const string DescriptionRu = "DescriptionRu";
            public const string Price = "Price";
            public const string DiscountValue = "DiscountValue";
            public const string PhotoUrl = "PhotoUrl";
            public const string IsAvailable = "IsAvailable";
            public const string CreatedAt = "CreatedAt";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _MenuItems.PropertyNames.Id;
					ht[MenuID] = _MenuItems.PropertyNames.MenuID;
					ht[PlaceID] = _MenuItems.PropertyNames.PlaceID;
					ht[Name] = _MenuItems.PropertyNames.Name;
					ht[NameEn] = _MenuItems.PropertyNames.NameEn;
					ht[NameRu] = _MenuItems.PropertyNames.NameRu;
					ht[Description] = _MenuItems.PropertyNames.Description;
					ht[DescriptionEn] = _MenuItems.PropertyNames.DescriptionEn;
					ht[DescriptionRu] = _MenuItems.PropertyNames.DescriptionRu;
					ht[Price] = _MenuItems.PropertyNames.Price;
					ht[DiscountValue] = _MenuItems.PropertyNames.DiscountValue;
					ht[PhotoUrl] = _MenuItems.PropertyNames.PhotoUrl;
					ht[IsAvailable] = _MenuItems.PropertyNames.IsAvailable;
					ht[CreatedAt] = _MenuItems.PropertyNames.CreatedAt;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string MenuID = "MenuID";
            public const string PlaceID = "PlaceID";
            public const string Name = "Name";
            public const string NameEn = "NameEn";
            public const string NameRu = "NameRu";
            public const string Description = "Description";
            public const string DescriptionEn = "DescriptionEn";
            public const string DescriptionRu = "DescriptionRu";
            public const string Price = "Price";
            public const string DiscountValue = "DiscountValue";
            public const string PhotoUrl = "PhotoUrl";
            public const string IsAvailable = "IsAvailable";
            public const string CreatedAt = "CreatedAt";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _MenuItems.ColumnNames.Id;
					ht[MenuID] = _MenuItems.ColumnNames.MenuID;
					ht[PlaceID] = _MenuItems.ColumnNames.PlaceID;
					ht[Name] = _MenuItems.ColumnNames.Name;
					ht[NameEn] = _MenuItems.ColumnNames.NameEn;
					ht[NameRu] = _MenuItems.ColumnNames.NameRu;
					ht[Description] = _MenuItems.ColumnNames.Description;
					ht[DescriptionEn] = _MenuItems.ColumnNames.DescriptionEn;
					ht[DescriptionRu] = _MenuItems.ColumnNames.DescriptionRu;
					ht[Price] = _MenuItems.ColumnNames.Price;
					ht[DiscountValue] = _MenuItems.ColumnNames.DiscountValue;
					ht[PhotoUrl] = _MenuItems.ColumnNames.PhotoUrl;
					ht[IsAvailable] = _MenuItems.ColumnNames.IsAvailable;
					ht[CreatedAt] = _MenuItems.ColumnNames.CreatedAt;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string MenuID = "s_MenuID";
            public const string PlaceID = "s_PlaceID";
            public const string Name = "s_Name";
            public const string NameEn = "s_NameEn";
            public const string NameRu = "s_NameRu";
            public const string Description = "s_Description";
            public const string DescriptionEn = "s_DescriptionEn";
            public const string DescriptionRu = "s_DescriptionRu";
            public const string Price = "s_Price";
            public const string DiscountValue = "s_DiscountValue";
            public const string PhotoUrl = "s_PhotoUrl";
            public const string IsAvailable = "s_IsAvailable";
            public const string CreatedAt = "s_CreatedAt";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual int MenuID
	    {
			get
	        {
				return base.Getint(ColumnNames.MenuID);
			}
			set
	        {
				base.Setint(ColumnNames.MenuID, value);
			}
		}

		public virtual int PlaceID
	    {
			get
	        {
				return base.Getint(ColumnNames.PlaceID);
			}
			set
	        {
				base.Setint(ColumnNames.PlaceID, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string NameEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameEn);
			}
			set
	        {
				base.Setstring(ColumnNames.NameEn, value);
			}
		}

		public virtual string NameRu
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameRu);
			}
			set
	        {
				base.Setstring(ColumnNames.NameRu, value);
			}
		}

		public virtual string Description
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description);
			}
			set
	        {
				base.Setstring(ColumnNames.Description, value);
			}
		}

		public virtual string DescriptionEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.DescriptionEn);
			}
			set
	        {
				base.Setstring(ColumnNames.DescriptionEn, value);
			}
		}

		public virtual string DescriptionRu
	    {
			get
	        {
				return base.Getstring(ColumnNames.DescriptionRu);
			}
			set
	        {
				base.Setstring(ColumnNames.DescriptionRu, value);
			}
		}

		public virtual decimal Price
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.Price);
			}
			set
	        {
				base.Setdecimal(ColumnNames.Price, value);
			}
		}

		public virtual decimal DiscountValue
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.DiscountValue);
			}
			set
	        {
				base.Setdecimal(ColumnNames.DiscountValue, value);
			}
		}

		public virtual string PhotoUrl
	    {
			get
	        {
				return base.Getstring(ColumnNames.PhotoUrl);
			}
			set
	        {
				base.Setstring(ColumnNames.PhotoUrl, value);
			}
		}

		public virtual bool IsAvailable
	    {
			get
	        {
				return base.Getbool(ColumnNames.IsAvailable);
			}
			set
	        {
				base.Setbool(ColumnNames.IsAvailable, value);
			}
		}

		public virtual DateTime CreatedAt
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.CreatedAt);
			}
			set
	        {
				base.SetDateTime(ColumnNames.CreatedAt, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_MenuID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MenuID) ? string.Empty : base.GetintAsString(ColumnNames.MenuID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MenuID);
				else
					this.MenuID = base.SetintAsString(ColumnNames.MenuID, value);
			}
		}

		public virtual string s_PlaceID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PlaceID) ? string.Empty : base.GetintAsString(ColumnNames.PlaceID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PlaceID);
				else
					this.PlaceID = base.SetintAsString(ColumnNames.PlaceID, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_NameEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameEn) ? string.Empty : base.GetstringAsString(ColumnNames.NameEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameEn);
				else
					this.NameEn = base.SetstringAsString(ColumnNames.NameEn, value);
			}
		}

		public virtual string s_NameRu
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameRu) ? string.Empty : base.GetstringAsString(ColumnNames.NameRu);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameRu);
				else
					this.NameRu = base.SetstringAsString(ColumnNames.NameRu, value);
			}
		}

		public virtual string s_Description
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description) ? string.Empty : base.GetstringAsString(ColumnNames.Description);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description);
				else
					this.Description = base.SetstringAsString(ColumnNames.Description, value);
			}
		}

		public virtual string s_DescriptionEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DescriptionEn) ? string.Empty : base.GetstringAsString(ColumnNames.DescriptionEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DescriptionEn);
				else
					this.DescriptionEn = base.SetstringAsString(ColumnNames.DescriptionEn, value);
			}
		}

		public virtual string s_DescriptionRu
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DescriptionRu) ? string.Empty : base.GetstringAsString(ColumnNames.DescriptionRu);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DescriptionRu);
				else
					this.DescriptionRu = base.SetstringAsString(ColumnNames.DescriptionRu, value);
			}
		}

		public virtual string s_Price
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Price) ? string.Empty : base.GetdecimalAsString(ColumnNames.Price);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Price);
				else
					this.Price = base.SetdecimalAsString(ColumnNames.Price, value);
			}
		}

		public virtual string s_DiscountValue
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DiscountValue) ? string.Empty : base.GetdecimalAsString(ColumnNames.DiscountValue);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DiscountValue);
				else
					this.DiscountValue = base.SetdecimalAsString(ColumnNames.DiscountValue, value);
			}
		}

		public virtual string s_PhotoUrl
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PhotoUrl) ? string.Empty : base.GetstringAsString(ColumnNames.PhotoUrl);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PhotoUrl);
				else
					this.PhotoUrl = base.SetstringAsString(ColumnNames.PhotoUrl, value);
			}
		}

		public virtual string s_IsAvailable
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.IsAvailable) ? string.Empty : base.GetboolAsString(ColumnNames.IsAvailable);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.IsAvailable);
				else
					this.IsAvailable = base.SetboolAsString(ColumnNames.IsAvailable, value);
			}
		}

		public virtual string s_CreatedAt
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CreatedAt) ? string.Empty : base.GetDateTimeAsString(ColumnNames.CreatedAt);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CreatedAt);
				else
					this.CreatedAt = base.SetDateTimeAsString(ColumnNames.CreatedAt, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MenuID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MenuID, Parameters.MenuID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PlaceID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PlaceID, Parameters.PlaceID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameRu
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameRu, Parameters.NameRu);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DescriptionEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DescriptionEn, Parameters.DescriptionEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DescriptionRu
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DescriptionRu, Parameters.DescriptionRu);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Price
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Price, Parameters.Price);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DiscountValue
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DiscountValue, Parameters.DiscountValue);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PhotoUrl
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PhotoUrl, Parameters.PhotoUrl);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter IsAvailable
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.IsAvailable, Parameters.IsAvailable);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CreatedAt
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CreatedAt, Parameters.CreatedAt);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter MenuID
		    {
				get
		        {
					if(_MenuID_W == null)
	        	    {
						_MenuID_W = TearOff.MenuID;
					}
					return _MenuID_W;
				}
			}

			public WhereParameter PlaceID
		    {
				get
		        {
					if(_PlaceID_W == null)
	        	    {
						_PlaceID_W = TearOff.PlaceID;
					}
					return _PlaceID_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public WhereParameter NameRu
		    {
				get
		        {
					if(_NameRu_W == null)
	        	    {
						_NameRu_W = TearOff.NameRu;
					}
					return _NameRu_W;
				}
			}

			public WhereParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public WhereParameter DescriptionEn
		    {
				get
		        {
					if(_DescriptionEn_W == null)
	        	    {
						_DescriptionEn_W = TearOff.DescriptionEn;
					}
					return _DescriptionEn_W;
				}
			}

			public WhereParameter DescriptionRu
		    {
				get
		        {
					if(_DescriptionRu_W == null)
	        	    {
						_DescriptionRu_W = TearOff.DescriptionRu;
					}
					return _DescriptionRu_W;
				}
			}

			public WhereParameter Price
		    {
				get
		        {
					if(_Price_W == null)
	        	    {
						_Price_W = TearOff.Price;
					}
					return _Price_W;
				}
			}

			public WhereParameter DiscountValue
		    {
				get
		        {
					if(_DiscountValue_W == null)
	        	    {
						_DiscountValue_W = TearOff.DiscountValue;
					}
					return _DiscountValue_W;
				}
			}

			public WhereParameter PhotoUrl
		    {
				get
		        {
					if(_PhotoUrl_W == null)
	        	    {
						_PhotoUrl_W = TearOff.PhotoUrl;
					}
					return _PhotoUrl_W;
				}
			}

			public WhereParameter IsAvailable
		    {
				get
		        {
					if(_IsAvailable_W == null)
	        	    {
						_IsAvailable_W = TearOff.IsAvailable;
					}
					return _IsAvailable_W;
				}
			}

			public WhereParameter CreatedAt
		    {
				get
		        {
					if(_CreatedAt_W == null)
	        	    {
						_CreatedAt_W = TearOff.CreatedAt;
					}
					return _CreatedAt_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _MenuID_W = null;
			private WhereParameter _PlaceID_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _NameEn_W = null;
			private WhereParameter _NameRu_W = null;
			private WhereParameter _Description_W = null;
			private WhereParameter _DescriptionEn_W = null;
			private WhereParameter _DescriptionRu_W = null;
			private WhereParameter _Price_W = null;
			private WhereParameter _DiscountValue_W = null;
			private WhereParameter _PhotoUrl_W = null;
			private WhereParameter _IsAvailable_W = null;
			private WhereParameter _CreatedAt_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_MenuID_W = null;
				_PlaceID_W = null;
				_Name_W = null;
				_NameEn_W = null;
				_NameRu_W = null;
				_Description_W = null;
				_DescriptionEn_W = null;
				_DescriptionRu_W = null;
				_Price_W = null;
				_DiscountValue_W = null;
				_PhotoUrl_W = null;
				_IsAvailable_W = null;
				_CreatedAt_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MenuID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MenuID, Parameters.MenuID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PlaceID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PlaceID, Parameters.PlaceID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameRu
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameRu, Parameters.NameRu);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DescriptionEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DescriptionEn, Parameters.DescriptionEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DescriptionRu
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DescriptionRu, Parameters.DescriptionRu);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Price
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Price, Parameters.Price);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DiscountValue
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DiscountValue, Parameters.DiscountValue);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PhotoUrl
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PhotoUrl, Parameters.PhotoUrl);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter IsAvailable
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.IsAvailable, Parameters.IsAvailable);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CreatedAt
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CreatedAt, Parameters.CreatedAt);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter MenuID
		    {
				get
		        {
					if(_MenuID_W == null)
	        	    {
						_MenuID_W = TearOff.MenuID;
					}
					return _MenuID_W;
				}
			}

			public AggregateParameter PlaceID
		    {
				get
		        {
					if(_PlaceID_W == null)
	        	    {
						_PlaceID_W = TearOff.PlaceID;
					}
					return _PlaceID_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public AggregateParameter NameRu
		    {
				get
		        {
					if(_NameRu_W == null)
	        	    {
						_NameRu_W = TearOff.NameRu;
					}
					return _NameRu_W;
				}
			}

			public AggregateParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public AggregateParameter DescriptionEn
		    {
				get
		        {
					if(_DescriptionEn_W == null)
	        	    {
						_DescriptionEn_W = TearOff.DescriptionEn;
					}
					return _DescriptionEn_W;
				}
			}

			public AggregateParameter DescriptionRu
		    {
				get
		        {
					if(_DescriptionRu_W == null)
	        	    {
						_DescriptionRu_W = TearOff.DescriptionRu;
					}
					return _DescriptionRu_W;
				}
			}

			public AggregateParameter Price
		    {
				get
		        {
					if(_Price_W == null)
	        	    {
						_Price_W = TearOff.Price;
					}
					return _Price_W;
				}
			}

			public AggregateParameter DiscountValue
		    {
				get
		        {
					if(_DiscountValue_W == null)
	        	    {
						_DiscountValue_W = TearOff.DiscountValue;
					}
					return _DiscountValue_W;
				}
			}

			public AggregateParameter PhotoUrl
		    {
				get
		        {
					if(_PhotoUrl_W == null)
	        	    {
						_PhotoUrl_W = TearOff.PhotoUrl;
					}
					return _PhotoUrl_W;
				}
			}

			public AggregateParameter IsAvailable
		    {
				get
		        {
					if(_IsAvailable_W == null)
	        	    {
						_IsAvailable_W = TearOff.IsAvailable;
					}
					return _IsAvailable_W;
				}
			}

			public AggregateParameter CreatedAt
		    {
				get
		        {
					if(_CreatedAt_W == null)
	        	    {
						_CreatedAt_W = TearOff.CreatedAt;
					}
					return _CreatedAt_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _MenuID_W = null;
			private AggregateParameter _PlaceID_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _NameEn_W = null;
			private AggregateParameter _NameRu_W = null;
			private AggregateParameter _Description_W = null;
			private AggregateParameter _DescriptionEn_W = null;
			private AggregateParameter _DescriptionRu_W = null;
			private AggregateParameter _Price_W = null;
			private AggregateParameter _DiscountValue_W = null;
			private AggregateParameter _PhotoUrl_W = null;
			private AggregateParameter _IsAvailable_W = null;
			private AggregateParameter _CreatedAt_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_MenuID_W = null;
				_PlaceID_W = null;
				_Name_W = null;
				_NameEn_W = null;
				_NameRu_W = null;
				_Description_W = null;
				_DescriptionEn_W = null;
				_DescriptionRu_W = null;
				_Price_W = null;
				_DiscountValue_W = null;
				_PhotoUrl_W = null;
				_IsAvailable_W = null;
				_CreatedAt_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_MenuItemsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_MenuItemsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_MenuItemsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.MenuID);
			p.SourceColumn = ColumnNames.MenuID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PlaceID);
			p.SourceColumn = ColumnNames.PlaceID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameEn);
			p.SourceColumn = ColumnNames.NameEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameRu);
			p.SourceColumn = ColumnNames.NameRu;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description);
			p.SourceColumn = ColumnNames.Description;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DescriptionEn);
			p.SourceColumn = ColumnNames.DescriptionEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DescriptionRu);
			p.SourceColumn = ColumnNames.DescriptionRu;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Price);
			p.SourceColumn = ColumnNames.Price;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DiscountValue);
			p.SourceColumn = ColumnNames.DiscountValue;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.PhotoUrl);
			p.SourceColumn = ColumnNames.PhotoUrl;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.IsAvailable);
			p.SourceColumn = ColumnNames.IsAvailable;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CreatedAt);
			p.SourceColumn = ColumnNames.CreatedAt;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
