
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _Menus : SqlClientEntity
	{
		public _Menus()
		{
			this.QuerySource = "Menus";
			this.MappingName = "Menus";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_MenusLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id, Id);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_MenusLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter NameEn
			{
				get
				{
					return new SqlParameter("@NameEn", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter NameRu
			{
				get
				{
					return new SqlParameter("@NameRu", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter Categories_id
			{
				get
				{
					return new SqlParameter("@Categories_id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Description
			{
				get
				{
					return new SqlParameter("@Description", SqlDbType.NVarChar, 255);
				}
			}
			
			public static SqlParameter DescriptionEn
			{
				get
				{
					return new SqlParameter("@DescriptionEn", SqlDbType.NVarChar, 255);
				}
			}
			
			public static SqlParameter DescriptionRu
			{
				get
				{
					return new SqlParameter("@DescriptionRu", SqlDbType.NVarChar, 255);
				}
			}
			
			public static SqlParameter CreatedAt
			{
				get
				{
					return new SqlParameter("@CreatedAt", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string Name = "Name";
            public const string NameEn = "NameEn";
            public const string NameRu = "NameRu";
            public const string Categories_id = "Categories_id";
            public const string Description = "Description";
            public const string DescriptionEn = "DescriptionEn";
            public const string DescriptionRu = "DescriptionRu";
            public const string CreatedAt = "CreatedAt";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Menus.PropertyNames.Id;
					ht[Name] = _Menus.PropertyNames.Name;
					ht[NameEn] = _Menus.PropertyNames.NameEn;
					ht[NameRu] = _Menus.PropertyNames.NameRu;
					ht[Categories_id] = _Menus.PropertyNames.Categories_id;
					ht[Description] = _Menus.PropertyNames.Description;
					ht[DescriptionEn] = _Menus.PropertyNames.DescriptionEn;
					ht[DescriptionRu] = _Menus.PropertyNames.DescriptionRu;
					ht[CreatedAt] = _Menus.PropertyNames.CreatedAt;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Name = "Name";
            public const string NameEn = "NameEn";
            public const string NameRu = "NameRu";
            public const string Categories_id = "Categories_id";
            public const string Description = "Description";
            public const string DescriptionEn = "DescriptionEn";
            public const string DescriptionRu = "DescriptionRu";
            public const string CreatedAt = "CreatedAt";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Menus.ColumnNames.Id;
					ht[Name] = _Menus.ColumnNames.Name;
					ht[NameEn] = _Menus.ColumnNames.NameEn;
					ht[NameRu] = _Menus.ColumnNames.NameRu;
					ht[Categories_id] = _Menus.ColumnNames.Categories_id;
					ht[Description] = _Menus.ColumnNames.Description;
					ht[DescriptionEn] = _Menus.ColumnNames.DescriptionEn;
					ht[DescriptionRu] = _Menus.ColumnNames.DescriptionRu;
					ht[CreatedAt] = _Menus.ColumnNames.CreatedAt;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Name = "s_Name";
            public const string NameEn = "s_NameEn";
            public const string NameRu = "s_NameRu";
            public const string Categories_id = "s_Categories_id";
            public const string Description = "s_Description";
            public const string DescriptionEn = "s_DescriptionEn";
            public const string DescriptionRu = "s_DescriptionRu";
            public const string CreatedAt = "s_CreatedAt";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string NameEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameEn);
			}
			set
	        {
				base.Setstring(ColumnNames.NameEn, value);
			}
		}

		public virtual string NameRu
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameRu);
			}
			set
	        {
				base.Setstring(ColumnNames.NameRu, value);
			}
		}

		public virtual int Categories_id
	    {
			get
	        {
				return base.Getint(ColumnNames.Categories_id);
			}
			set
	        {
				base.Setint(ColumnNames.Categories_id, value);
			}
		}

		public virtual string Description
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description);
			}
			set
	        {
				base.Setstring(ColumnNames.Description, value);
			}
		}

		public virtual string DescriptionEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.DescriptionEn);
			}
			set
	        {
				base.Setstring(ColumnNames.DescriptionEn, value);
			}
		}

		public virtual string DescriptionRu
	    {
			get
	        {
				return base.Getstring(ColumnNames.DescriptionRu);
			}
			set
	        {
				base.Setstring(ColumnNames.DescriptionRu, value);
			}
		}

		public virtual DateTime CreatedAt
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.CreatedAt);
			}
			set
	        {
				base.SetDateTime(ColumnNames.CreatedAt, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_NameEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameEn) ? string.Empty : base.GetstringAsString(ColumnNames.NameEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameEn);
				else
					this.NameEn = base.SetstringAsString(ColumnNames.NameEn, value);
			}
		}

		public virtual string s_NameRu
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameRu) ? string.Empty : base.GetstringAsString(ColumnNames.NameRu);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameRu);
				else
					this.NameRu = base.SetstringAsString(ColumnNames.NameRu, value);
			}
		}

		public virtual string s_Categories_id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Categories_id) ? string.Empty : base.GetintAsString(ColumnNames.Categories_id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Categories_id);
				else
					this.Categories_id = base.SetintAsString(ColumnNames.Categories_id, value);
			}
		}

		public virtual string s_Description
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description) ? string.Empty : base.GetstringAsString(ColumnNames.Description);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description);
				else
					this.Description = base.SetstringAsString(ColumnNames.Description, value);
			}
		}

		public virtual string s_DescriptionEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DescriptionEn) ? string.Empty : base.GetstringAsString(ColumnNames.DescriptionEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DescriptionEn);
				else
					this.DescriptionEn = base.SetstringAsString(ColumnNames.DescriptionEn, value);
			}
		}

		public virtual string s_DescriptionRu
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DescriptionRu) ? string.Empty : base.GetstringAsString(ColumnNames.DescriptionRu);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DescriptionRu);
				else
					this.DescriptionRu = base.SetstringAsString(ColumnNames.DescriptionRu, value);
			}
		}

		public virtual string s_CreatedAt
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.CreatedAt) ? string.Empty : base.GetDateTimeAsString(ColumnNames.CreatedAt);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.CreatedAt);
				else
					this.CreatedAt = base.SetDateTimeAsString(ColumnNames.CreatedAt, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameRu
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameRu, Parameters.NameRu);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Categories_id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Categories_id, Parameters.Categories_id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DescriptionEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DescriptionEn, Parameters.DescriptionEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DescriptionRu
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DescriptionRu, Parameters.DescriptionRu);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter CreatedAt
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.CreatedAt, Parameters.CreatedAt);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public WhereParameter NameRu
		    {
				get
		        {
					if(_NameRu_W == null)
	        	    {
						_NameRu_W = TearOff.NameRu;
					}
					return _NameRu_W;
				}
			}

			public WhereParameter Categories_id
		    {
				get
		        {
					if(_Categories_id_W == null)
	        	    {
						_Categories_id_W = TearOff.Categories_id;
					}
					return _Categories_id_W;
				}
			}

			public WhereParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public WhereParameter DescriptionEn
		    {
				get
		        {
					if(_DescriptionEn_W == null)
	        	    {
						_DescriptionEn_W = TearOff.DescriptionEn;
					}
					return _DescriptionEn_W;
				}
			}

			public WhereParameter DescriptionRu
		    {
				get
		        {
					if(_DescriptionRu_W == null)
	        	    {
						_DescriptionRu_W = TearOff.DescriptionRu;
					}
					return _DescriptionRu_W;
				}
			}

			public WhereParameter CreatedAt
		    {
				get
		        {
					if(_CreatedAt_W == null)
	        	    {
						_CreatedAt_W = TearOff.CreatedAt;
					}
					return _CreatedAt_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _NameEn_W = null;
			private WhereParameter _NameRu_W = null;
			private WhereParameter _Categories_id_W = null;
			private WhereParameter _Description_W = null;
			private WhereParameter _DescriptionEn_W = null;
			private WhereParameter _DescriptionRu_W = null;
			private WhereParameter _CreatedAt_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_NameEn_W = null;
				_NameRu_W = null;
				_Categories_id_W = null;
				_Description_W = null;
				_DescriptionEn_W = null;
				_DescriptionRu_W = null;
				_CreatedAt_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameRu
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameRu, Parameters.NameRu);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Categories_id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Categories_id, Parameters.Categories_id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DescriptionEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DescriptionEn, Parameters.DescriptionEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DescriptionRu
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DescriptionRu, Parameters.DescriptionRu);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter CreatedAt
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.CreatedAt, Parameters.CreatedAt);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public AggregateParameter NameRu
		    {
				get
		        {
					if(_NameRu_W == null)
	        	    {
						_NameRu_W = TearOff.NameRu;
					}
					return _NameRu_W;
				}
			}

			public AggregateParameter Categories_id
		    {
				get
		        {
					if(_Categories_id_W == null)
	        	    {
						_Categories_id_W = TearOff.Categories_id;
					}
					return _Categories_id_W;
				}
			}

			public AggregateParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public AggregateParameter DescriptionEn
		    {
				get
		        {
					if(_DescriptionEn_W == null)
	        	    {
						_DescriptionEn_W = TearOff.DescriptionEn;
					}
					return _DescriptionEn_W;
				}
			}

			public AggregateParameter DescriptionRu
		    {
				get
		        {
					if(_DescriptionRu_W == null)
	        	    {
						_DescriptionRu_W = TearOff.DescriptionRu;
					}
					return _DescriptionRu_W;
				}
			}

			public AggregateParameter CreatedAt
		    {
				get
		        {
					if(_CreatedAt_W == null)
	        	    {
						_CreatedAt_W = TearOff.CreatedAt;
					}
					return _CreatedAt_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _NameEn_W = null;
			private AggregateParameter _NameRu_W = null;
			private AggregateParameter _Categories_id_W = null;
			private AggregateParameter _Description_W = null;
			private AggregateParameter _DescriptionEn_W = null;
			private AggregateParameter _DescriptionRu_W = null;
			private AggregateParameter _CreatedAt_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_NameEn_W = null;
				_NameRu_W = null;
				_Categories_id_W = null;
				_Description_W = null;
				_DescriptionEn_W = null;
				_DescriptionRu_W = null;
				_CreatedAt_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_MenusInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_MenusUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_MenusDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameEn);
			p.SourceColumn = ColumnNames.NameEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameRu);
			p.SourceColumn = ColumnNames.NameRu;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Categories_id);
			p.SourceColumn = ColumnNames.Categories_id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Description);
			p.SourceColumn = ColumnNames.Description;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DescriptionEn);
			p.SourceColumn = ColumnNames.DescriptionEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DescriptionRu);
			p.SourceColumn = ColumnNames.DescriptionRu;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.CreatedAt);
			p.SourceColumn = ColumnNames.CreatedAt;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
