
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _Orders : SqlClientEntity
	{
		public _Orders()
		{
			this.QuerySource = "Orders";
			this.MappingName = "Orders";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_OrdersLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id, Id);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_OrdersLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Address_id
			{
				get
				{
					return new SqlParameter("@Address_id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Odate
			{
				get
				{
					return new SqlParameter("@Odate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter DeliveryCost
			{
				get
				{
					return new SqlParameter("@DeliveryCost", SqlDbType.Money, 0);
				}
			}
			
			public static SqlParameter Delivered
			{
				get
				{
					return new SqlParameter("@Delivered", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string Address_id = "Address_id";
            public const string Odate = "Odate";
            public const string DeliveryCost = "DeliveryCost";
            public const string Delivered = "Delivered";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Orders.PropertyNames.Id;
					ht[Address_id] = _Orders.PropertyNames.Address_id;
					ht[Odate] = _Orders.PropertyNames.Odate;
					ht[DeliveryCost] = _Orders.PropertyNames.DeliveryCost;
					ht[Delivered] = _Orders.PropertyNames.Delivered;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Address_id = "Address_id";
            public const string Odate = "Odate";
            public const string DeliveryCost = "DeliveryCost";
            public const string Delivered = "Delivered";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Orders.ColumnNames.Id;
					ht[Address_id] = _Orders.ColumnNames.Address_id;
					ht[Odate] = _Orders.ColumnNames.Odate;
					ht[DeliveryCost] = _Orders.ColumnNames.DeliveryCost;
					ht[Delivered] = _Orders.ColumnNames.Delivered;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Address_id = "s_Address_id";
            public const string Odate = "s_Odate";
            public const string DeliveryCost = "s_DeliveryCost";
            public const string Delivered = "s_Delivered";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual int Address_id
	    {
			get
	        {
				return base.Getint(ColumnNames.Address_id);
			}
			set
	        {
				base.Setint(ColumnNames.Address_id, value);
			}
		}

		public virtual DateTime Odate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.Odate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.Odate, value);
			}
		}

		public virtual decimal DeliveryCost
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.DeliveryCost);
			}
			set
	        {
				base.Setdecimal(ColumnNames.DeliveryCost, value);
			}
		}

		public virtual bool Delivered
	    {
			get
	        {
				return base.Getbool(ColumnNames.Delivered);
			}
			set
	        {
				base.Setbool(ColumnNames.Delivered, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Address_id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Address_id) ? string.Empty : base.GetintAsString(ColumnNames.Address_id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Address_id);
				else
					this.Address_id = base.SetintAsString(ColumnNames.Address_id, value);
			}
		}

		public virtual string s_Odate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Odate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.Odate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Odate);
				else
					this.Odate = base.SetDateTimeAsString(ColumnNames.Odate, value);
			}
		}

		public virtual string s_DeliveryCost
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DeliveryCost) ? string.Empty : base.GetdecimalAsString(ColumnNames.DeliveryCost);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DeliveryCost);
				else
					this.DeliveryCost = base.SetdecimalAsString(ColumnNames.DeliveryCost, value);
			}
		}

		public virtual string s_Delivered
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Delivered) ? string.Empty : base.GetboolAsString(ColumnNames.Delivered);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Delivered);
				else
					this.Delivered = base.SetboolAsString(ColumnNames.Delivered, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Address_id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Address_id, Parameters.Address_id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Odate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Odate, Parameters.Odate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DeliveryCost
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DeliveryCost, Parameters.DeliveryCost);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Delivered
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Delivered, Parameters.Delivered);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Address_id
		    {
				get
		        {
					if(_Address_id_W == null)
	        	    {
						_Address_id_W = TearOff.Address_id;
					}
					return _Address_id_W;
				}
			}

			public WhereParameter Odate
		    {
				get
		        {
					if(_Odate_W == null)
	        	    {
						_Odate_W = TearOff.Odate;
					}
					return _Odate_W;
				}
			}

			public WhereParameter DeliveryCost
		    {
				get
		        {
					if(_DeliveryCost_W == null)
	        	    {
						_DeliveryCost_W = TearOff.DeliveryCost;
					}
					return _DeliveryCost_W;
				}
			}

			public WhereParameter Delivered
		    {
				get
		        {
					if(_Delivered_W == null)
	        	    {
						_Delivered_W = TearOff.Delivered;
					}
					return _Delivered_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Address_id_W = null;
			private WhereParameter _Odate_W = null;
			private WhereParameter _DeliveryCost_W = null;
			private WhereParameter _Delivered_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Address_id_W = null;
				_Odate_W = null;
				_DeliveryCost_W = null;
				_Delivered_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Address_id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Address_id, Parameters.Address_id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Odate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Odate, Parameters.Odate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DeliveryCost
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DeliveryCost, Parameters.DeliveryCost);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Delivered
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Delivered, Parameters.Delivered);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Address_id
		    {
				get
		        {
					if(_Address_id_W == null)
	        	    {
						_Address_id_W = TearOff.Address_id;
					}
					return _Address_id_W;
				}
			}

			public AggregateParameter Odate
		    {
				get
		        {
					if(_Odate_W == null)
	        	    {
						_Odate_W = TearOff.Odate;
					}
					return _Odate_W;
				}
			}

			public AggregateParameter DeliveryCost
		    {
				get
		        {
					if(_DeliveryCost_W == null)
	        	    {
						_DeliveryCost_W = TearOff.DeliveryCost;
					}
					return _DeliveryCost_W;
				}
			}

			public AggregateParameter Delivered
		    {
				get
		        {
					if(_Delivered_W == null)
	        	    {
						_Delivered_W = TearOff.Delivered;
					}
					return _Delivered_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Address_id_W = null;
			private AggregateParameter _Odate_W = null;
			private AggregateParameter _DeliveryCost_W = null;
			private AggregateParameter _Delivered_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Address_id_W = null;
				_Odate_W = null;
				_DeliveryCost_W = null;
				_Delivered_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_OrdersInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_OrdersUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_OrdersDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Address_id);
			p.SourceColumn = ColumnNames.Address_id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Odate);
			p.SourceColumn = ColumnNames.Odate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.DeliveryCost);
			p.SourceColumn = ColumnNames.DeliveryCost;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Delivered);
			p.SourceColumn = ColumnNames.Delivered;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
