
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _Pages : SqlClientEntity
	{
		public _Pages()
		{
			this.QuerySource = "Pages";
			this.MappingName = "Pages";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_PagesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ID, ID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_PagesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ID
			{
				get
				{
					return new SqlParameter("@ID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter NameAr
			{
				get
				{
					return new SqlParameter("@NameAr", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter NameEn
			{
				get
				{
					return new SqlParameter("@NameEn", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter ContentAr
			{
				get
				{
					return new SqlParameter("@ContentAr", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter ContentEn
			{
				get
				{
					return new SqlParameter("@ContentEn", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter LastUpdate
			{
				get
				{
					return new SqlParameter("@LastUpdate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter ReadCount
			{
				get
				{
					return new SqlParameter("@ReadCount", SqlDbType.BigInt, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ID = "ID";
            public const string NameAr = "NameAr";
            public const string NameEn = "NameEn";
            public const string ContentAr = "ContentAr";
            public const string ContentEn = "ContentEn";
            public const string LastUpdate = "LastUpdate";
            public const string ReadCount = "ReadCount";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _Pages.PropertyNames.ID;
					ht[NameAr] = _Pages.PropertyNames.NameAr;
					ht[NameEn] = _Pages.PropertyNames.NameEn;
					ht[ContentAr] = _Pages.PropertyNames.ContentAr;
					ht[ContentEn] = _Pages.PropertyNames.ContentEn;
					ht[LastUpdate] = _Pages.PropertyNames.LastUpdate;
					ht[ReadCount] = _Pages.PropertyNames.ReadCount;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ID = "ID";
            public const string NameAr = "NameAr";
            public const string NameEn = "NameEn";
            public const string ContentAr = "ContentAr";
            public const string ContentEn = "ContentEn";
            public const string LastUpdate = "LastUpdate";
            public const string ReadCount = "ReadCount";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _Pages.ColumnNames.ID;
					ht[NameAr] = _Pages.ColumnNames.NameAr;
					ht[NameEn] = _Pages.ColumnNames.NameEn;
					ht[ContentAr] = _Pages.ColumnNames.ContentAr;
					ht[ContentEn] = _Pages.ColumnNames.ContentEn;
					ht[LastUpdate] = _Pages.ColumnNames.LastUpdate;
					ht[ReadCount] = _Pages.ColumnNames.ReadCount;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ID = "s_ID";
            public const string NameAr = "s_NameAr";
            public const string NameEn = "s_NameEn";
            public const string ContentAr = "s_ContentAr";
            public const string ContentEn = "s_ContentEn";
            public const string LastUpdate = "s_LastUpdate";
            public const string ReadCount = "s_ReadCount";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ID
	    {
			get
	        {
				return base.Getint(ColumnNames.ID);
			}
			set
	        {
				base.Setint(ColumnNames.ID, value);
			}
		}

		public virtual string NameAr
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameAr);
			}
			set
	        {
				base.Setstring(ColumnNames.NameAr, value);
			}
		}

		public virtual string NameEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameEn);
			}
			set
	        {
				base.Setstring(ColumnNames.NameEn, value);
			}
		}

		public virtual string ContentAr
	    {
			get
	        {
				return base.Getstring(ColumnNames.ContentAr);
			}
			set
	        {
				base.Setstring(ColumnNames.ContentAr, value);
			}
		}

		public virtual string ContentEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.ContentEn);
			}
			set
	        {
				base.Setstring(ColumnNames.ContentEn, value);
			}
		}

		public virtual DateTime LastUpdate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.LastUpdate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.LastUpdate, value);
			}
		}

		public virtual long ReadCount
	    {
			get
	        {
				return base.Getlong(ColumnNames.ReadCount);
			}
			set
	        {
				base.Setlong(ColumnNames.ReadCount, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ID) ? string.Empty : base.GetintAsString(ColumnNames.ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ID);
				else
					this.ID = base.SetintAsString(ColumnNames.ID, value);
			}
		}

		public virtual string s_NameAr
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameAr) ? string.Empty : base.GetstringAsString(ColumnNames.NameAr);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameAr);
				else
					this.NameAr = base.SetstringAsString(ColumnNames.NameAr, value);
			}
		}

		public virtual string s_NameEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameEn) ? string.Empty : base.GetstringAsString(ColumnNames.NameEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameEn);
				else
					this.NameEn = base.SetstringAsString(ColumnNames.NameEn, value);
			}
		}

		public virtual string s_ContentAr
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ContentAr) ? string.Empty : base.GetstringAsString(ColumnNames.ContentAr);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ContentAr);
				else
					this.ContentAr = base.SetstringAsString(ColumnNames.ContentAr, value);
			}
		}

		public virtual string s_ContentEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ContentEn) ? string.Empty : base.GetstringAsString(ColumnNames.ContentEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ContentEn);
				else
					this.ContentEn = base.SetstringAsString(ColumnNames.ContentEn, value);
			}
		}

		public virtual string s_LastUpdate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.LastUpdate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.LastUpdate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.LastUpdate);
				else
					this.LastUpdate = base.SetDateTimeAsString(ColumnNames.LastUpdate, value);
			}
		}

		public virtual string s_ReadCount
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ReadCount) ? string.Empty : base.GetlongAsString(ColumnNames.ReadCount);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ReadCount);
				else
					this.ReadCount = base.SetlongAsString(ColumnNames.ReadCount, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameAr
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameAr, Parameters.NameAr);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ContentAr
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ContentAr, Parameters.ContentAr);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ContentEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ContentEn, Parameters.ContentEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter LastUpdate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.LastUpdate, Parameters.LastUpdate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ReadCount
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ReadCount, Parameters.ReadCount);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public WhereParameter NameAr
		    {
				get
		        {
					if(_NameAr_W == null)
	        	    {
						_NameAr_W = TearOff.NameAr;
					}
					return _NameAr_W;
				}
			}

			public WhereParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public WhereParameter ContentAr
		    {
				get
		        {
					if(_ContentAr_W == null)
	        	    {
						_ContentAr_W = TearOff.ContentAr;
					}
					return _ContentAr_W;
				}
			}

			public WhereParameter ContentEn
		    {
				get
		        {
					if(_ContentEn_W == null)
	        	    {
						_ContentEn_W = TearOff.ContentEn;
					}
					return _ContentEn_W;
				}
			}

			public WhereParameter LastUpdate
		    {
				get
		        {
					if(_LastUpdate_W == null)
	        	    {
						_LastUpdate_W = TearOff.LastUpdate;
					}
					return _LastUpdate_W;
				}
			}

			public WhereParameter ReadCount
		    {
				get
		        {
					if(_ReadCount_W == null)
	        	    {
						_ReadCount_W = TearOff.ReadCount;
					}
					return _ReadCount_W;
				}
			}

			private WhereParameter _ID_W = null;
			private WhereParameter _NameAr_W = null;
			private WhereParameter _NameEn_W = null;
			private WhereParameter _ContentAr_W = null;
			private WhereParameter _ContentEn_W = null;
			private WhereParameter _LastUpdate_W = null;
			private WhereParameter _ReadCount_W = null;

			public void WhereClauseReset()
			{
				_ID_W = null;
				_NameAr_W = null;
				_NameEn_W = null;
				_ContentAr_W = null;
				_ContentEn_W = null;
				_LastUpdate_W = null;
				_ReadCount_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameAr
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameAr, Parameters.NameAr);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ContentAr
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ContentAr, Parameters.ContentAr);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ContentEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ContentEn, Parameters.ContentEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter LastUpdate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.LastUpdate, Parameters.LastUpdate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ReadCount
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ReadCount, Parameters.ReadCount);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public AggregateParameter NameAr
		    {
				get
		        {
					if(_NameAr_W == null)
	        	    {
						_NameAr_W = TearOff.NameAr;
					}
					return _NameAr_W;
				}
			}

			public AggregateParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public AggregateParameter ContentAr
		    {
				get
		        {
					if(_ContentAr_W == null)
	        	    {
						_ContentAr_W = TearOff.ContentAr;
					}
					return _ContentAr_W;
				}
			}

			public AggregateParameter ContentEn
		    {
				get
		        {
					if(_ContentEn_W == null)
	        	    {
						_ContentEn_W = TearOff.ContentEn;
					}
					return _ContentEn_W;
				}
			}

			public AggregateParameter LastUpdate
		    {
				get
		        {
					if(_LastUpdate_W == null)
	        	    {
						_LastUpdate_W = TearOff.LastUpdate;
					}
					return _LastUpdate_W;
				}
			}

			public AggregateParameter ReadCount
		    {
				get
		        {
					if(_ReadCount_W == null)
	        	    {
						_ReadCount_W = TearOff.ReadCount;
					}
					return _ReadCount_W;
				}
			}

			private AggregateParameter _ID_W = null;
			private AggregateParameter _NameAr_W = null;
			private AggregateParameter _NameEn_W = null;
			private AggregateParameter _ContentAr_W = null;
			private AggregateParameter _ContentEn_W = null;
			private AggregateParameter _LastUpdate_W = null;
			private AggregateParameter _ReadCount_W = null;

			public void AggregateClauseReset()
			{
				_ID_W = null;
				_NameAr_W = null;
				_NameEn_W = null;
				_ContentAr_W = null;
				_ContentEn_W = null;
				_LastUpdate_W = null;
				_ReadCount_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_PagesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_PagesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_PagesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameAr);
			p.SourceColumn = ColumnNames.NameAr;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.NameEn);
			p.SourceColumn = ColumnNames.NameEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ContentAr);
			p.SourceColumn = ColumnNames.ContentAr;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ContentEn);
			p.SourceColumn = ColumnNames.ContentEn;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.LastUpdate);
			p.SourceColumn = ColumnNames.LastUpdate;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ReadCount);
			p.SourceColumn = ColumnNames.ReadCount;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
