
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;


namespace DMS
{
	public abstract class _Privilages : SqlClientEntity
	{
		public _Privilages()
		{
			this.QuerySource = "Privilages";
			this.MappingName = "Privilages";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_PrivilagesLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int Id)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.Id, Id);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_PrivilagesLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Role_id
			{
				get
				{
					return new SqlParameter("@Role_id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Page_id
			{
				get
				{
					return new SqlParameter("@Page_id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter R
			{
				get
				{
					return new SqlParameter("@R", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter W
			{
				get
				{
					return new SqlParameter("@W", SqlDbType.Bit, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string Role_id = "Role_id";
            public const string Page_id = "Page_id";
            public const string R = "R";
            public const string W = "W";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Privilages.PropertyNames.Id;
					ht[Role_id] = _Privilages.PropertyNames.Role_id;
					ht[Page_id] = _Privilages.PropertyNames.Page_id;
					ht[R] = _Privilages.PropertyNames.R;
					ht[W] = _Privilages.PropertyNames.W;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Role_id = "Role_id";
            public const string Page_id = "Page_id";
            public const string R = "R";
            public const string W = "W";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = _Privilages.ColumnNames.Id;
					ht[Role_id] = _Privilages.ColumnNames.Role_id;
					ht[Page_id] = _Privilages.ColumnNames.Page_id;
					ht[R] = _Privilages.ColumnNames.R;
					ht[W] = _Privilages.ColumnNames.W;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Role_id = "s_Role_id";
            public const string Page_id = "s_Page_id";
            public const string R = "s_R";
            public const string W = "s_W";

		}
		#endregion		
		
		#region Properties
	
		public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual int Role_id
	    {
			get
	        {
				return base.Getint(ColumnNames.Role_id);
			}
			set
	        {
				base.Setint(ColumnNames.Role_id, value);
			}
		}

		public virtual int Page_id
	    {
			get
	        {
				return base.Getint(ColumnNames.Page_id);
			}
			set
	        {
				base.Setint(ColumnNames.Page_id, value);
			}
		}

		public virtual bool R
	    {
			get
	        {
				return base.Getbool(ColumnNames.R);
			}
			set
	        {
				base.Setbool(ColumnNames.R, value);
			}
		}

		public virtual bool W
	    {
			get
	        {
				return base.Getbool(ColumnNames.W);
			}
			set
	        {
				base.Setbool(ColumnNames.W, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Role_id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Role_id) ? string.Empty : base.GetintAsString(ColumnNames.Role_id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Role_id);
				else
					this.Role_id = base.SetintAsString(ColumnNames.Role_id, value);
			}
		}

		public virtual string s_Page_id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Page_id) ? string.Empty : base.GetintAsString(ColumnNames.Page_id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Page_id);
				else
					this.Page_id = base.SetintAsString(ColumnNames.Page_id, value);
			}
		}

		public virtual string s_R
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.R) ? string.Empty : base.GetboolAsString(ColumnNames.R);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.R);
				else
					this.R = base.SetboolAsString(ColumnNames.R, value);
			}
		}

		public virtual string s_W
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.W) ? string.Empty : base.GetboolAsString(ColumnNames.W);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.W);
				else
					this.W = base.SetboolAsString(ColumnNames.W, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Role_id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Role_id, Parameters.Role_id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Page_id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Page_id, Parameters.Page_id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter R
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.R, Parameters.R);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter W
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.W, Parameters.W);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Role_id
		    {
				get
		        {
					if(_Role_id_W == null)
	        	    {
						_Role_id_W = TearOff.Role_id;
					}
					return _Role_id_W;
				}
			}

			public WhereParameter Page_id
		    {
				get
		        {
					if(_Page_id_W == null)
	        	    {
						_Page_id_W = TearOff.Page_id;
					}
					return _Page_id_W;
				}
			}

			public WhereParameter R
		    {
				get
		        {
					if(_R_W == null)
	        	    {
						_R_W = TearOff.R;
					}
					return _R_W;
				}
			}

			public WhereParameter W
		    {
				get
		        {
					if(_W_W == null)
	        	    {
						_W_W = TearOff.W;
					}
					return _W_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Role_id_W = null;
			private WhereParameter _Page_id_W = null;
			private WhereParameter _R_W = null;
			private WhereParameter _W_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Role_id_W = null;
				_Page_id_W = null;
				_R_W = null;
				_W_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Role_id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Role_id, Parameters.Role_id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Page_id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Page_id, Parameters.Page_id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter R
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.R, Parameters.R);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter W
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.W, Parameters.W);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Role_id
		    {
				get
		        {
					if(_Role_id_W == null)
	        	    {
						_Role_id_W = TearOff.Role_id;
					}
					return _Role_id_W;
				}
			}

			public AggregateParameter Page_id
		    {
				get
		        {
					if(_Page_id_W == null)
	        	    {
						_Page_id_W = TearOff.Page_id;
					}
					return _Page_id_W;
				}
			}

			public AggregateParameter R
		    {
				get
		        {
					if(_R_W == null)
	        	    {
						_R_W = TearOff.R;
					}
					return _R_W;
				}
			}

			public AggregateParameter W
		    {
				get
		        {
					if(_W_W == null)
	        	    {
						_W_W = TearOff.W;
					}
					return _W_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Role_id_W = null;
			private AggregateParameter _Page_id_W = null;
			private AggregateParameter _R_W = null;
			private AggregateParameter _W_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Role_id_W = null;
				_Page_id_W = null;
				_R_W = null;
				_W_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_PrivilagesInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.Id.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_PrivilagesUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_PrivilagesDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.Id);
			p.SourceColumn = ColumnNames.Id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Role_id);
			p.SourceColumn = ColumnNames.Role_id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Page_id);
			p.SourceColumn = ColumnNames.Page_id;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.R);
			p.SourceColumn = ColumnNames.R;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.W);
			p.SourceColumn = ColumnNames.W;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
