const texts = {
    CheckoutTitle: "الدفع",
    UpdateOrder: "تعديل الطلب",
    Hot: "حار",
    SpecialOrder: "طلب خاص",
    Item: "الصنف",
    Quantity: "الكمية",
    Price: "السعر",
    Total: "الإجمالي",
    Remove: "إزالة",
    EmptyCart: "السلة فارغة!",
    Subtotal: "المجموع الفرعي",
    DeliveryFee: "رسوم التوصيل",
    FinalTotal: "المبلغ الإجمالي",
    AddToCartToast: "تمت الإضافة إلى السلة!",
    CartEmptyTotal: "الإجمالي: 00.00 ج.م",
    ConfirmEmptyCart: "هل أنت متأكد من إفراغ السلة؟",
    CartEmptied: "تم إفراغ السلة!",
    AddItemDifferentShopTitle: "صنف من متجر آخر",
    AddItemDifferentShopText: "هل تريد إضافة هذا الصنف من متجر آخر؟",
    CannotAddDifferentAreaTitle: "لا يمكن الإضافة",
    CannotAddDifferentAreaText: "لا يمكن إضافة أصناف من منطقة مختلفة.",
    YesAdd: "نعم، أضف",
    Cancel: "إلغاء",
    Ok: "حسناً",
    Currency: "ج.م", 
    CartIsEmpty: "سلة المشتريات فارغة!",
    DefaultShopName: "المتجر",
    HotSpice: "حار"
};
