const texts = {
    CheckoutTitle: "Checkout",
    UpdateOrder: "Update Order",
    Hot: "Hot",
    SpecialOrder: "Special Order",
    Item: "Item",
    Quantity: "Quantity",
    Price: "Price",
    Total: "Total",
    Remove: "Remove",
    EmptyCart: "Cart is empty!",
    Subtotal: "Subtotal",
    DeliveryFee: "Delivery Fee",
    FinalTotal: "Final Total",
    AddToCartToast: "Added to cart!",
    CartEmptyTotal: "Total: EGP 00.00",
    ConfirmEmptyCart: "Are you sure you want to empty the cart?",
    CartEmptied: "Cart emptied!",
    AddItemDifferentShopTitle: "Item from different shop",
    AddItemDifferentShopText: "Do you want to add this item from another shop?",
    CannotAddDifferentAreaTitle: "Cannot add",
    CannotAddDifferentAreaText: "You cannot add items from a different area.",
    YesAdd: "Yes, add item",
    Cancel: "Cancel",
    Ok: "OK",
    Currency: "EGP", // Egyptian Pound

    // Toast Messages
    AddedToCartDefault: "Added to cart!",
    AddedToCartPrefix: "Added",
    AddedToCartSuffix: "to cart!",
    CartEmptied: "Shopping cart emptied.",
    AddedFromDifferentShop: "Product added from a different shop!",

    // Confirmation and Warning Messages (Swal)
    CannotAddDifferentAreaTitle: "Oops!",
    CannotAddDifferentAreaText: "You cannot add products from two different areas in the same order.",
    AddItemDifferentShopTitle: "Alert!",
    AddItemDifferentShopText: "You have items from another shop. Do you want to add this item and proceed with the new shop?",
    ConfirmEmptyCart: "Are you sure you want to empty the shopping cart?",

    // Checkout Page Interface
    CartIsEmpty: "The shopping cart is empty!",
    DefaultShopName: "The Shop",
    HotSpice: "Spicy",
    PromoCodeTitle: "Promo Code",
    OrderDiscount: "Order Discount",
    ShippingDiscount: "Shipping Discount",
    PromoPlaceholder: "Enter promo code",
    Apply: "Apply",
    PaymentMethodTitle: "Payment Method",
    Cash: "Cash",
    Visa: "Visa",
    EWallet: "Electronic Wallet",
    VodafoneCash: "Vodafone Cash",
    WalletNumber: "Wallet / Account number you are transferring from",
    PaymentProof: "Payment proof image",
    AttachProof: "Attach transfer image",
    Extras: "Extras",
    Notes: "Notes",
    TotalCostLabel: "Total Cost:",
    Delivery: "Delivery",
    Pickup: "Pickup",
    InShop: "In-Shop",
    InShopSummaryMsg: "We are not responsible if you miss or do not show up at the restaurant",
    InShopMethodTitle: "In-Shop Order",
    EatInShop: "Eat In-Shop",
    SubtotalLabel: "Subtotal:",
    DeliveryLabel: "Delivery:",
    PickupWarning: "⚠️ Store pickup applies to all shops in the order. We are not responsible if you change your mind later.",
    AddNotesPlaceholder: "Add your notes here...",
    ShippingDiscountPlaceholder: "Shipping discount code",
    OrderDiscountPlaceholder: "Order discount code",
    EnterPromoCodeError: "Please enter the promo code",
    CheckingPromo: "Checking",
    PromoAppliedSuccess: "{0} applied successfully!",
    PromoSavedAmount: "Saved {0} {1} ({2}%)",
    PromoErrorInvalid: "❌ Invalid promo code for the selected discount type",
    PromoSummaryApplied: "Promo code applied: Saved {0} {1} ({2}% discount on {3})",
    PickupSummaryMsg: "The selected pickup method is store pickup",
    ChooseLocation: "Choose your location",
    WhatsAppTitle: "Contact us via WhatsApp",
    EditEmail: "Edit Email",
    EditPassword: "Edit Password",
    OnlyOnePromoClarification: "ℹ️ Only one promo code can be applied per order.",
    RemoveCoupon: "Remove Coupon",
    OrderDetailsTitle: "Order Details",
    EditOrder: "Edit Order",
    LoadingOrder: "Loading order...",
    SelectedDeliveryInfo: "Selected Delivery Info",
    AddressLabel: "Address",
    MobileLabel: "Mobile Number",
    PhoneLabel: "Phone Number",
    StreetLabel: "Street",
    BuildingLabel: "Building",
    FloorLabel: "Floor",
    ApartmentNoLabel: "Apartment No",
    GovernorateLabel: "Governorate",
    AreaLabel: "Area",
    InstructionsLabel: "Additional Instructions",
    AddressTypeLabel: "Address Type",
    AddEditAddressBtn: "Add / Edit Address",
    ChooseDeliveryLocation: "Please choose delivery location",
    PayerPhone: "Wallet / Account number you are transferring from",
    PaymentProofImage: "Payment proof image",
    FinalTotalLabel: "Final Total",
    DeliveryFeeLabel: "Delivery Fee:",
    PromoInfo: "ℹ️ Only one promo code can be applied per order.",
    EnterPromoCode: "Enter promo code",
    DeliveryTimeTitle: "Order Delivery Time",
    ExpectedDeliveryTime: "Expected Delivery Time",
    RescheduleBtn: "Reschedule Order",
    DeliveryTimeHint: "Delivery will be in",
    Minutes: "minutes",
    OrderSummaryTitle: "Order Summary",
    TotalDeliveryTime: "Total Delivery Time",
    ConfirmRescheduleTitle: "Confirm Time",
    ConfirmRescheduleText: "Are you sure you want to change the delivery time to {0}?",
    CustomDeliveryTime: "Custom scheduled time",
    Confirm: "Confirm",
    DeliveryMethodTitle: "Delivery Method",
    PickupMethodTitle: "Pickup Method",
    ContactMethodTitle: "Contact Method",
    ShareMessage: "Order now from {0} via Fast Delivery! {1}",
    ShareTitle: "Share Shop",
    RingBell: "Ring Bell",
    WhatsApp: "WhatsApp",
    CallPhone: "Phone Call",
    PrepTime: "Order Preparation Time",
    Applied: "(Applied)",
    HomeDelivery: "Home Delivery",
    PickupFromStore: "Pickup from Store",
    ScheduledFor: "Scheduled for",
    PrepTimeHint: "Preparation will be in",
    ScheduledAt: "Scheduled at"
};
