const texts = {
    CheckoutTitle: "Оформление заказа",
    UpdateOrder: "Обновить заказ",
    Hot: "Горячее",
    SpecialOrder: "Специальный заказ",
    Item: "Товар",
    Quantity: "Количество",
    Price: "Цена",
    Total: "Сумма",
    Remove: "Удалить",
    EmptyCart: "Корзина пуста!",
    Subtotal: "Промежуточный итог",
    DeliveryFee: "Стоимость доставки",
    FinalTotal: "Итоговая сумма",
    AddToCartToast: "Добавлено в корзину!",
    CartEmptyTotal: "Итого: EGP 00.00",
    ConfirmEmptyCart: "Вы уверены, что хотите очистить корзину?",
    CartEmptied: "Корзина очищена!",
    AddItemDifferentShopTitle: "Товар из другого магазина",
    AddItemDifferentShopText: "Хотите добавить этот товар из другого магазина?",
    CannotAddDifferentAreaTitle: "Невозможно добавить",
    CannotAddDifferentAreaText: "Вы не можете добавлять товары из другой зоны.",
    YesAdd: "Да, добавить товар",
    Cancel: "Отмена",
    Ok: "ОК",
    Currency: "EGP", // Египетские фунты

    // Сообщения Toast
    AddedToCartDefault: "Добавлено в корзину!",
    AddedToCartPrefix: "Добавлено",
    AddedToCartSuffix: "в корзину!",
    CartEmptied: "Корзина опустошена.",
    AddedFromDifferentShop: "Товар добавлен из другого магазина!",

    // Сообщения подтверждения и предупреждения (Swal)
    CannotAddDifferentAreaTitle: "Ой!",
    CannotAddDifferentAreaText: "Вы не можете добавить товары из двух разных регионов в один и тот же заказ.",
    AddItemDifferentShopTitle: "Внимание!",
    AddItemDifferentShopText: "У вас есть товары из другого магазина. Вы хотите добавить этот товар и продолжить с новым магазином?",
    ConfirmEmptyCart: "Вы уверены, что хотите очистить корзину?",

    // Интерфейс страницы оформления заказа (Checkout)
    CartIsEmpty: "Корзина пуста!",
    DefaultShopName: "Магазин",
    HotSpice: "Острый",
    PromoCodeTitle: "Промокод",
    OrderDiscount: "Скидка на заказ",
    ShippingDiscount: "Скидка на доставку",
    PromoPlaceholder: "Введите промокод",
    Apply: "Применить",
    PaymentMethodTitle: "Способ оплаты",
    Cash: "Наличные",
    Visa: "Visa",
    EWallet: "Электронный кошелек",
    VodafoneCash: "Vodafone Cash",
    WalletNumber: "Номер кошелька / счета, с которого вы переводите",
    PaymentProof: "Фото подтверждения платежа",
    AttachProof: "Прикрепить фото перевода",
    Extras: "Добавки",
    Notes: "Примечания",
    TotalCostLabel: "Общая стоимость:",
    Delivery: "Доставка",
    Pickup: "Самовывоз",
    InShop: "В магазине",
    InShopSummaryMsg: "Мы не несем ответственности, если вы не явитесь или опоздаете в ресторан",
    InShopMethodTitle: "Заказ в магазине",
    EatInShop: "Поесть в магазине",
    SubtotalLabel: "Промежуточный итог:",
    DeliveryLabel: "Доставка:",
    PickupWarning: "⚠️ Самовывоз из магазина распространяется на все магазины в заказе. Мы не несем ответственности, если вы передумаете позже.",
    AddNotesPlaceholder: "Добавьте свои примечания здесь...",
    ShippingDiscountPlaceholder: "Код скидки на доставку",
    OrderDiscountPlaceholder: "Код скидки на заказ",
    EnterPromoCodeError: "Пожалуйста, введите промокод",
    CheckingPromo: "Проверка",
    PromoAppliedSuccess: "{0} успешно применен!",
    PromoSavedAmount: "Сэкономлено {0} {1} ({2}%)",
    PromoErrorInvalid: "❌ Неверный промокод для выбранного типа скидки",
    PromoSummaryApplied: "Промокод применен: Сэкономлено {0} {1} ({2}% скидка на {3})",
    PickupSummaryMsg: "Выбранный способ получения - самовывоз из магазина",
    ChooseLocation: "Выберите ваше местоположение",
    WhatsAppTitle: "Свяжитесь с нами через WhatsApp",
    EditEmail: "Изменить Email",
    EditPassword: "Изменить пароль",
    OnlyOnePromoClarification: "ℹ️ Одновременно можно применить только по одному промокоду для заказа и для доставки.",
    RemoveCoupon: "Удалить купон",
    OrderDetailsTitle: "Детали заказа",
    EditOrder: "Изменить заказ",
    LoadingOrder: "Загрузка заказа...",
    SelectedDeliveryInfo: "Выбранная информация о доставке",
    AddressLabel: "Адрес",
    MobileLabel: "Номер мобильного",
    PhoneLabel: "Номер телефона",
    StreetLabel: "Улица",
    BuildingLabel: "Здание",
    FloorLabel: "Этаж",
    ApartmentNoLabel: "№ квартиры",
    GovernorateLabel: "Губернаторство",
    AreaLabel: "Район",
    InstructionsLabel: "Дополнительные инструкции",
    AddressTypeLabel: "Тип адреса",
    AddEditAddressBtn: "Добавить / Изменить адрес",
    ChooseDeliveryLocation: "Пожалуйста, выберите место доставки",
    PayerPhone: "Номер кошелька / счета, с которого вы переводите",
    PaymentProofImage: "Фото подтверждения платежа",
    FinalTotalLabel: "Итоговая сумма",
    DeliveryFeeLabel: "Стоимость доставки:",
    PromoInfo: "ℹ️ Одновременно можно применить только по одному промокоду для заказа и для доставки.",
    EnterPromoCode: "Введите промокод",
    DeliveryTimeTitle: "Время доставки заказа",
    ExpectedDeliveryTime: "Ожидаемое время доставки",
    RescheduleBtn: "Перенести заказ",
    DeliveryTimeHint: "Доставка будет через",
    Minutes: "минут",
    OrderSummaryTitle: "Сводка заказа",
    TotalDeliveryTime: "Общее время доставки",
    SelectedDeliveryInfo: "Выбранная информация о доставке",
    ConfirmRescheduleTitle: "Подтвердить время",
    ConfirmRescheduleText: "Вы уверены, что хотите изменить время доставки на {0}?",
    CustomDeliveryTime: "Пользовательское время",
    Confirm: "Подтвердить",
    DeliveryMethodTitle: "Способ доставки",
    PickupMethodTitle: "Способ получения",
    ContactMethodTitle: "Способ связи",
    ShareMessage: "Заказывайте в {0} через Fast Delivery! {1}",
    ShareTitle: "Поделиться магазином",
    Reset: "Сброс",
    RingBell: "Позвонить в звонок",
    WhatsApp: "WhatsApp",
    CallPhone: "Телефонный звонок",
    PrepTime: "Время подготовки заказа",
    Applied: "(Применено)",
    HomeDelivery: "Доставка на дом",
    PickupFromStore: "Самовывоз из магазина",
    ScheduledFor: "Запланировано на",
    PrepTimeHint: "Подготовка будет через",
    ScheduledAt: "Запланировано на",
    MultiShopPromoWarning: "Примечание: Промокоды на заказ нельзя использовать при заказе из нескольких магазинов.",
    OrderPromoDisabledForMultiShop: "Промокод на заказ недоступен, так как ваш заказ содержит товары из нескольких магазинов.",
    FirstOrderFreeDelivery: "0.00 благодаря вашему первому заказу! 🎉",
    FileErrorTitle: "Ошибка файла",
    FileErrorText: "Пожалуйста, выберите корректный файл изображения",
    ProofRequiredTitle: "Требуется подтверждение оплаты",
    ProofRequiredText: "Пожалуйста, прикрепите подтверждение оплаты (скриншот перевода)",
    PhoneRequiredTitle: "Требуется номер телефона",
    PhoneRequiredText: "Пожалуйста, введите номер телефона, с которого был перевод",
    EmptyCartTitle: "Корзина пуста",
    OrderSuccessTitle: "Ваш заказ успешно отправлен и ожидает выполнения",
    ContinueBtn: "Продолжить",
    ErrorTitle: "Ошибка",
    ConnectionErrorTitle: "Ошибка соединения",
    ConnectionErrorText: "Произошла ошибка во время выполнения операции"
};
window.texts = window.texts || texts;
