/*
'===============================================================================
'  Generated From - CSharp_dOOdads_View.vbgen
'
'  The supporting base class SqlClientEntity is in the 
'  Architecture directory in "dOOdads".
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;



namespace DMS
{
	public class vw_Privilages : SqlClientEntity
	{
		public vw_Privilages()
		{
			this.QuerySource = "vw_Privilages";
			this.MappingName = "vw_Privilages";
		}	
	
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			return base.Query.Load();
		}
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
	
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 400);
				}
			}
			
			public static SqlParameter R
			{
				get
				{
					return new SqlParameter("@R", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter W
			{
				get
				{
					return new SqlParameter("@W", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter UID
			{
				get
				{
					return new SqlParameter("@UID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion	
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string Name = "name";
            public const string R = "R";
            public const string W = "W";
            public const string UID = "UID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = vw_Privilages.PropertyNames.Id;
					ht[Name] = vw_Privilages.PropertyNames.Name;
					ht[R] = vw_Privilages.PropertyNames.R;
					ht[W] = vw_Privilages.PropertyNames.W;
					ht[UID] = vw_Privilages.PropertyNames.UID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Name = "Name";
            public const string R = "R";
            public const string W = "W";
            public const string UID = "UID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = vw_Privilages.ColumnNames.Id;
					ht[Name] = vw_Privilages.ColumnNames.Name;
					ht[R] = vw_Privilages.ColumnNames.R;
					ht[W] = vw_Privilages.ColumnNames.W;
					ht[UID] = vw_Privilages.ColumnNames.UID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Name = "s_Name";
            public const string R = "s_R";
            public const string W = "s_W";
            public const string UID = "s_UID";

		}
		#endregion	
		
		#region Properties
			public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual bool R
	    {
			get
	        {
				return base.Getbool(ColumnNames.R);
			}
			set
	        {
				base.Setbool(ColumnNames.R, value);
			}
		}

		public virtual bool W
	    {
			get
	        {
				return base.Getbool(ColumnNames.W);
			}
			set
	        {
				base.Setbool(ColumnNames.W, value);
			}
		}

		public virtual int UID
	    {
			get
	        {
				return base.Getint(ColumnNames.UID);
			}
			set
	        {
				base.Setint(ColumnNames.UID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_R
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.R) ? string.Empty : base.GetboolAsString(ColumnNames.R);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.R);
				else
					this.R = base.SetboolAsString(ColumnNames.R, value);
			}
		}

		public virtual string s_W
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.W) ? string.Empty : base.GetboolAsString(ColumnNames.W);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.W);
				else
					this.W = base.SetboolAsString(ColumnNames.W, value);
			}
		}

		public virtual string s_UID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UID) ? string.Empty : base.GetintAsString(ColumnNames.UID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UID);
				else
					this.UID = base.SetintAsString(ColumnNames.UID, value);
			}
		}


		#endregion			
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter R
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.R, Parameters.R);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter W
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.W, Parameters.W);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UID, Parameters.UID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter R
		    {
				get
		        {
					if(_R_W == null)
	        	    {
						_R_W = TearOff.R;
					}
					return _R_W;
				}
			}

			public WhereParameter W
		    {
				get
		        {
					if(_W_W == null)
	        	    {
						_W_W = TearOff.W;
					}
					return _W_W;
				}
			}

			public WhereParameter UID
		    {
				get
		        {
					if(_UID_W == null)
	        	    {
						_UID_W = TearOff.UID;
					}
					return _UID_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _R_W = null;
			private WhereParameter _W_W = null;
			private WhereParameter _UID_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_R_W = null;
				_W_W = null;
				_UID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter R
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.R, Parameters.R);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter W
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.W, Parameters.W);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UID, Parameters.UID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter R
		    {
				get
		        {
					if(_R_W == null)
	        	    {
						_R_W = TearOff.R;
					}
					return _R_W;
				}
			}

			public AggregateParameter W
		    {
				get
		        {
					if(_W_W == null)
	        	    {
						_W_W = TearOff.W;
					}
					return _W_W;
				}
			}

			public AggregateParameter UID
		    {
				get
		        {
					if(_UID_W == null)
	        	    {
						_UID_W = TearOff.UID;
					}
					return _UID_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _R_W = null;
			private AggregateParameter _W_W = null;
			private AggregateParameter _UID_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_R_W = null;
				_W_W = null;
				_UID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
			return null;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
			return null;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
			return null;
		}
	}
}
