/*
'===============================================================================
'  Generated From - CSharp_dOOdads_View.vbgen
'
'  The supporting base class SqlClientEntity is in the 
'  Architecture directory in "dOOdads".
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;



namespace DMS
{
	public class vw_Places : SqlClientEntity
	{
		public vw_Places()
		{
			this.QuerySource = "vw_Places";
			this.MappingName = "vw_Places";
		}	
	
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			return base.Query.Load();
		}
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
	
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter NameEn
			{
				get
				{
					return new SqlParameter("@NameEn", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter Address
			{
				get
				{
					return new SqlParameter("@Address", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter Description
			{
				get
				{
					return new SqlParameter("@Description", SqlDbType.NVarChar, 1073741823);
				}
			}
			
			public static SqlParameter DeliveredTime
			{
				get
				{
					return new SqlParameter("@DeliveredTime", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter MinOrder
			{
				get
				{
					return new SqlParameter("@MinOrder", SqlDbType.Money, 0);
				}
			}
			
			public static SqlParameter PhotoPath
			{
				get
				{
					return new SqlParameter("@PhotoPath", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Active
			{
				get
				{
					return new SqlParameter("@Active", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter Category
			{
				get
				{
					return new SqlParameter("@Category", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter Categories_id
			{
				get
				{
					return new SqlParameter("@Categories_id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Area
			{
				get
				{
					return new SqlParameter("@Area", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Gov
			{
				get
				{
					return new SqlParameter("@Gov", SqlDbType.NVarChar, 150);
				}
			}
			
			public static SqlParameter Rate
			{
				get
				{
					return new SqlParameter("@Rate", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion	
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "id";
            public const string Name = "Name";
            public const string NameEn = "NameEn";
            public const string Address = "Address";
            public const string Description = "Description";
            public const string DeliveredTime = "DeliveredTime";
            public const string MinOrder = "MinOrder";
            public const string PhotoPath = "PhotoPath";
            public const string Active = "Active";
            public const string Category = "Category";
            public const string Categories_id = "Categories_id";
            public const string Area = "Area";
            public const string Gov = "Gov";
            public const string Rate = "Rate";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = vw_Places.PropertyNames.Id;
					ht[Name] = vw_Places.PropertyNames.Name;
					ht[NameEn] = vw_Places.PropertyNames.NameEn;
					ht[Address] = vw_Places.PropertyNames.Address;
					ht[Description] = vw_Places.PropertyNames.Description;
					ht[DeliveredTime] = vw_Places.PropertyNames.DeliveredTime;
					ht[MinOrder] = vw_Places.PropertyNames.MinOrder;
					ht[PhotoPath] = vw_Places.PropertyNames.PhotoPath;
					ht[Active] = vw_Places.PropertyNames.Active;
					ht[Category] = vw_Places.PropertyNames.Category;
					ht[Categories_id] = vw_Places.PropertyNames.Categories_id;
					ht[Area] = vw_Places.PropertyNames.Area;
					ht[Gov] = vw_Places.PropertyNames.Gov;
					ht[Rate] = vw_Places.PropertyNames.Rate;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Name = "Name";
            public const string NameEn = "NameEn";
            public const string Address = "Address";
            public const string Description = "Description";
            public const string DeliveredTime = "DeliveredTime";
            public const string MinOrder = "MinOrder";
            public const string PhotoPath = "PhotoPath";
            public const string Active = "Active";
            public const string Category = "Category";
            public const string Categories_id = "Categories_id";
            public const string Area = "Area";
            public const string Gov = "Gov";
            public const string Rate = "Rate";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = vw_Places.ColumnNames.Id;
					ht[Name] = vw_Places.ColumnNames.Name;
					ht[NameEn] = vw_Places.ColumnNames.NameEn;
					ht[Address] = vw_Places.ColumnNames.Address;
					ht[Description] = vw_Places.ColumnNames.Description;
					ht[DeliveredTime] = vw_Places.ColumnNames.DeliveredTime;
					ht[MinOrder] = vw_Places.ColumnNames.MinOrder;
					ht[PhotoPath] = vw_Places.ColumnNames.PhotoPath;
					ht[Active] = vw_Places.ColumnNames.Active;
					ht[Category] = vw_Places.ColumnNames.Category;
					ht[Categories_id] = vw_Places.ColumnNames.Categories_id;
					ht[Area] = vw_Places.ColumnNames.Area;
					ht[Gov] = vw_Places.ColumnNames.Gov;
					ht[Rate] = vw_Places.ColumnNames.Rate;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Name = "s_Name";
            public const string NameEn = "s_NameEn";
            public const string Address = "s_Address";
            public const string Description = "s_Description";
            public const string DeliveredTime = "s_DeliveredTime";
            public const string MinOrder = "s_MinOrder";
            public const string PhotoPath = "s_PhotoPath";
            public const string Active = "s_Active";
            public const string Category = "s_Category";
            public const string Categories_id = "s_Categories_id";
            public const string Area = "s_Area";
            public const string Gov = "s_Gov";
            public const string Rate = "s_Rate";

		}
		#endregion	
		
		#region Properties
			public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string NameEn
	    {
			get
	        {
				return base.Getstring(ColumnNames.NameEn);
			}
			set
	        {
				base.Setstring(ColumnNames.NameEn, value);
			}
		}

		public virtual string Address
	    {
			get
	        {
				return base.Getstring(ColumnNames.Address);
			}
			set
	        {
				base.Setstring(ColumnNames.Address, value);
			}
		}

		public virtual string Description
	    {
			get
	        {
				return base.Getstring(ColumnNames.Description);
			}
			set
	        {
				base.Setstring(ColumnNames.Description, value);
			}
		}

		public virtual int DeliveredTime
	    {
			get
	        {
				return base.Getint(ColumnNames.DeliveredTime);
			}
			set
	        {
				base.Setint(ColumnNames.DeliveredTime, value);
			}
		}

		public virtual decimal MinOrder
	    {
			get
	        {
				return base.Getdecimal(ColumnNames.MinOrder);
			}
			set
	        {
				base.Setdecimal(ColumnNames.MinOrder, value);
			}
		}

		public virtual string PhotoPath
	    {
			get
	        {
				return base.Getstring(ColumnNames.PhotoPath);
			}
			set
	        {
				base.Setstring(ColumnNames.PhotoPath, value);
			}
		}

		public virtual bool Active
	    {
			get
	        {
				return base.Getbool(ColumnNames.Active);
			}
			set
	        {
				base.Setbool(ColumnNames.Active, value);
			}
		}

		public virtual string Category
	    {
			get
	        {
				return base.Getstring(ColumnNames.Category);
			}
			set
	        {
				base.Setstring(ColumnNames.Category, value);
			}
		}

		public virtual int Categories_id
	    {
			get
	        {
				return base.Getint(ColumnNames.Categories_id);
			}
			set
	        {
				base.Setint(ColumnNames.Categories_id, value);
			}
		}

		public virtual string Area
	    {
			get
	        {
				return base.Getstring(ColumnNames.Area);
			}
			set
	        {
				base.Setstring(ColumnNames.Area, value);
			}
		}

		public virtual string Gov
	    {
			get
	        {
				return base.Getstring(ColumnNames.Gov);
			}
			set
	        {
				base.Setstring(ColumnNames.Gov, value);
			}
		}

		public virtual int Rate
	    {
			get
	        {
				return base.Getint(ColumnNames.Rate);
			}
			set
	        {
				base.Setint(ColumnNames.Rate, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_NameEn
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.NameEn) ? string.Empty : base.GetstringAsString(ColumnNames.NameEn);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.NameEn);
				else
					this.NameEn = base.SetstringAsString(ColumnNames.NameEn, value);
			}
		}

		public virtual string s_Address
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Address) ? string.Empty : base.GetstringAsString(ColumnNames.Address);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Address);
				else
					this.Address = base.SetstringAsString(ColumnNames.Address, value);
			}
		}

		public virtual string s_Description
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Description) ? string.Empty : base.GetstringAsString(ColumnNames.Description);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Description);
				else
					this.Description = base.SetstringAsString(ColumnNames.Description, value);
			}
		}

		public virtual string s_DeliveredTime
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.DeliveredTime) ? string.Empty : base.GetintAsString(ColumnNames.DeliveredTime);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.DeliveredTime);
				else
					this.DeliveredTime = base.SetintAsString(ColumnNames.DeliveredTime, value);
			}
		}

		public virtual string s_MinOrder
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.MinOrder) ? string.Empty : base.GetdecimalAsString(ColumnNames.MinOrder);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.MinOrder);
				else
					this.MinOrder = base.SetdecimalAsString(ColumnNames.MinOrder, value);
			}
		}

		public virtual string s_PhotoPath
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PhotoPath) ? string.Empty : base.GetstringAsString(ColumnNames.PhotoPath);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PhotoPath);
				else
					this.PhotoPath = base.SetstringAsString(ColumnNames.PhotoPath, value);
			}
		}

		public virtual string s_Active
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Active) ? string.Empty : base.GetboolAsString(ColumnNames.Active);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Active);
				else
					this.Active = base.SetboolAsString(ColumnNames.Active, value);
			}
		}

		public virtual string s_Category
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Category) ? string.Empty : base.GetstringAsString(ColumnNames.Category);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Category);
				else
					this.Category = base.SetstringAsString(ColumnNames.Category, value);
			}
		}

		public virtual string s_Categories_id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Categories_id) ? string.Empty : base.GetintAsString(ColumnNames.Categories_id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Categories_id);
				else
					this.Categories_id = base.SetintAsString(ColumnNames.Categories_id, value);
			}
		}

		public virtual string s_Area
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Area) ? string.Empty : base.GetstringAsString(ColumnNames.Area);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Area);
				else
					this.Area = base.SetstringAsString(ColumnNames.Area, value);
			}
		}

		public virtual string s_Gov
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Gov) ? string.Empty : base.GetstringAsString(ColumnNames.Gov);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Gov);
				else
					this.Gov = base.SetstringAsString(ColumnNames.Gov, value);
			}
		}

		public virtual string s_Rate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Rate) ? string.Empty : base.GetintAsString(ColumnNames.Rate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Rate);
				else
					this.Rate = base.SetintAsString(ColumnNames.Rate, value);
			}
		}


		#endregion			
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter NameEn
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Address
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Address, Parameters.Address);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Description
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter DeliveredTime
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.DeliveredTime, Parameters.DeliveredTime);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter MinOrder
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.MinOrder, Parameters.MinOrder);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PhotoPath
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PhotoPath, Parameters.PhotoPath);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Active
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Active, Parameters.Active);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Category
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Category, Parameters.Category);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Categories_id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Categories_id, Parameters.Categories_id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Area
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Area, Parameters.Area);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Gov
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Gov, Parameters.Gov);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Rate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Rate, Parameters.Rate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public WhereParameter Address
		    {
				get
		        {
					if(_Address_W == null)
	        	    {
						_Address_W = TearOff.Address;
					}
					return _Address_W;
				}
			}

			public WhereParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public WhereParameter DeliveredTime
		    {
				get
		        {
					if(_DeliveredTime_W == null)
	        	    {
						_DeliveredTime_W = TearOff.DeliveredTime;
					}
					return _DeliveredTime_W;
				}
			}

			public WhereParameter MinOrder
		    {
				get
		        {
					if(_MinOrder_W == null)
	        	    {
						_MinOrder_W = TearOff.MinOrder;
					}
					return _MinOrder_W;
				}
			}

			public WhereParameter PhotoPath
		    {
				get
		        {
					if(_PhotoPath_W == null)
	        	    {
						_PhotoPath_W = TearOff.PhotoPath;
					}
					return _PhotoPath_W;
				}
			}

			public WhereParameter Active
		    {
				get
		        {
					if(_Active_W == null)
	        	    {
						_Active_W = TearOff.Active;
					}
					return _Active_W;
				}
			}

			public WhereParameter Category
		    {
				get
		        {
					if(_Category_W == null)
	        	    {
						_Category_W = TearOff.Category;
					}
					return _Category_W;
				}
			}

			public WhereParameter Categories_id
		    {
				get
		        {
					if(_Categories_id_W == null)
	        	    {
						_Categories_id_W = TearOff.Categories_id;
					}
					return _Categories_id_W;
				}
			}

			public WhereParameter Area
		    {
				get
		        {
					if(_Area_W == null)
	        	    {
						_Area_W = TearOff.Area;
					}
					return _Area_W;
				}
			}

			public WhereParameter Gov
		    {
				get
		        {
					if(_Gov_W == null)
	        	    {
						_Gov_W = TearOff.Gov;
					}
					return _Gov_W;
				}
			}

			public WhereParameter Rate
		    {
				get
		        {
					if(_Rate_W == null)
	        	    {
						_Rate_W = TearOff.Rate;
					}
					return _Rate_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _NameEn_W = null;
			private WhereParameter _Address_W = null;
			private WhereParameter _Description_W = null;
			private WhereParameter _DeliveredTime_W = null;
			private WhereParameter _MinOrder_W = null;
			private WhereParameter _PhotoPath_W = null;
			private WhereParameter _Active_W = null;
			private WhereParameter _Category_W = null;
			private WhereParameter _Categories_id_W = null;
			private WhereParameter _Area_W = null;
			private WhereParameter _Gov_W = null;
			private WhereParameter _Rate_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_NameEn_W = null;
				_Address_W = null;
				_Description_W = null;
				_DeliveredTime_W = null;
				_MinOrder_W = null;
				_PhotoPath_W = null;
				_Active_W = null;
				_Category_W = null;
				_Categories_id_W = null;
				_Area_W = null;
				_Gov_W = null;
				_Rate_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter NameEn
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.NameEn, Parameters.NameEn);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Address
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Address, Parameters.Address);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Description
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Description, Parameters.Description);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter DeliveredTime
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.DeliveredTime, Parameters.DeliveredTime);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter MinOrder
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.MinOrder, Parameters.MinOrder);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PhotoPath
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PhotoPath, Parameters.PhotoPath);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Active
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Active, Parameters.Active);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Category
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Category, Parameters.Category);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Categories_id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Categories_id, Parameters.Categories_id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Area
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Area, Parameters.Area);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Gov
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Gov, Parameters.Gov);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Rate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Rate, Parameters.Rate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter NameEn
		    {
				get
		        {
					if(_NameEn_W == null)
	        	    {
						_NameEn_W = TearOff.NameEn;
					}
					return _NameEn_W;
				}
			}

			public AggregateParameter Address
		    {
				get
		        {
					if(_Address_W == null)
	        	    {
						_Address_W = TearOff.Address;
					}
					return _Address_W;
				}
			}

			public AggregateParameter Description
		    {
				get
		        {
					if(_Description_W == null)
	        	    {
						_Description_W = TearOff.Description;
					}
					return _Description_W;
				}
			}

			public AggregateParameter DeliveredTime
		    {
				get
		        {
					if(_DeliveredTime_W == null)
	        	    {
						_DeliveredTime_W = TearOff.DeliveredTime;
					}
					return _DeliveredTime_W;
				}
			}

			public AggregateParameter MinOrder
		    {
				get
		        {
					if(_MinOrder_W == null)
	        	    {
						_MinOrder_W = TearOff.MinOrder;
					}
					return _MinOrder_W;
				}
			}

			public AggregateParameter PhotoPath
		    {
				get
		        {
					if(_PhotoPath_W == null)
	        	    {
						_PhotoPath_W = TearOff.PhotoPath;
					}
					return _PhotoPath_W;
				}
			}

			public AggregateParameter Active
		    {
				get
		        {
					if(_Active_W == null)
	        	    {
						_Active_W = TearOff.Active;
					}
					return _Active_W;
				}
			}

			public AggregateParameter Category
		    {
				get
		        {
					if(_Category_W == null)
	        	    {
						_Category_W = TearOff.Category;
					}
					return _Category_W;
				}
			}

			public AggregateParameter Categories_id
		    {
				get
		        {
					if(_Categories_id_W == null)
	        	    {
						_Categories_id_W = TearOff.Categories_id;
					}
					return _Categories_id_W;
				}
			}

			public AggregateParameter Area
		    {
				get
		        {
					if(_Area_W == null)
	        	    {
						_Area_W = TearOff.Area;
					}
					return _Area_W;
				}
			}

			public AggregateParameter Gov
		    {
				get
		        {
					if(_Gov_W == null)
	        	    {
						_Gov_W = TearOff.Gov;
					}
					return _Gov_W;
				}
			}

			public AggregateParameter Rate
		    {
				get
		        {
					if(_Rate_W == null)
	        	    {
						_Rate_W = TearOff.Rate;
					}
					return _Rate_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _NameEn_W = null;
			private AggregateParameter _Address_W = null;
			private AggregateParameter _Description_W = null;
			private AggregateParameter _DeliveredTime_W = null;
			private AggregateParameter _MinOrder_W = null;
			private AggregateParameter _PhotoPath_W = null;
			private AggregateParameter _Active_W = null;
			private AggregateParameter _Category_W = null;
			private AggregateParameter _Categories_id_W = null;
			private AggregateParameter _Area_W = null;
			private AggregateParameter _Gov_W = null;
			private AggregateParameter _Rate_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_NameEn_W = null;
				_Address_W = null;
				_Description_W = null;
				_DeliveredTime_W = null;
				_MinOrder_W = null;
				_PhotoPath_W = null;
				_Active_W = null;
				_Category_W = null;
				_Categories_id_W = null;
				_Area_W = null;
				_Gov_W = null;
				_Rate_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
			return null;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
			return null;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
			return null;
		}
	}
}
