/*
'===============================================================================
'  Generated From - CSharp_dOOdads_View.vbgen
'
'  The supporting base class SqlClientEntity is in the 
'  Architecture directory in "dOOdads".
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;



namespace DMS
{
	public class vw_Users : SqlClientEntity
	{
		public vw_Users()
		{
			this.QuerySource = "vw_Users";
			this.MappingName = "vw_Users";
		}	
	
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			return base.Query.Load();
		}
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
	
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter Id
			{
				get
				{
					return new SqlParameter("@Id", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter Lname
			{
				get
				{
					return new SqlParameter("@Lname", SqlDbType.NVarChar, 100);
				}
			}
			
			public static SqlParameter Email
			{
				get
				{
					return new SqlParameter("@Email", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter Gender
			{
				get
				{
					return new SqlParameter("@Gender", SqlDbType.Bit, 0);
				}
			}
			
			public static SqlParameter Bdate
			{
				get
				{
					return new SqlParameter("@Bdate", SqlDbType.DateTime, 0);
				}
			}
			
			public static SqlParameter Ocounts
			{
				get
				{
					return new SqlParameter("@Ocounts", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter PasswordHash
			{
				get
				{
					return new SqlParameter("@PasswordHash", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter Provider
			{
				get
				{
					return new SqlParameter("@Provider", SqlDbType.NVarChar, 50);
				}
			}
			
			public static SqlParameter ProviderId
			{
				get
				{
					return new SqlParameter("@ProviderId", SqlDbType.NVarChar, 200);
				}
			}
			
			public static SqlParameter Acounts
			{
				get
				{
					return new SqlParameter("@Acounts", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion	
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string Id = "Id";
            public const string Name = "Name";
            public const string Lname = "Lname";
            public const string Email = "Email";
            public const string Gender = "Gender";
            public const string Bdate = "Bdate";
            public const string Ocounts = "Ocounts";
            public const string PasswordHash = "PasswordHash";
            public const string Provider = "Provider";
            public const string ProviderId = "ProviderId";
            public const string Acounts = "Acounts";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = vw_Users.PropertyNames.Id;
					ht[Name] = vw_Users.PropertyNames.Name;
					ht[Lname] = vw_Users.PropertyNames.Lname;
					ht[Email] = vw_Users.PropertyNames.Email;
					ht[Gender] = vw_Users.PropertyNames.Gender;
					ht[Bdate] = vw_Users.PropertyNames.Bdate;
					ht[Ocounts] = vw_Users.PropertyNames.Ocounts;
					ht[PasswordHash] = vw_Users.PropertyNames.PasswordHash;
					ht[Provider] = vw_Users.PropertyNames.Provider;
					ht[ProviderId] = vw_Users.PropertyNames.ProviderId;
					ht[Acounts] = vw_Users.PropertyNames.Acounts;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string Id = "Id";
            public const string Name = "Name";
            public const string Lname = "Lname";
            public const string Email = "Email";
            public const string Gender = "Gender";
            public const string Bdate = "Bdate";
            public const string Ocounts = "Ocounts";
            public const string PasswordHash = "PasswordHash";
            public const string Provider = "Provider";
            public const string ProviderId = "ProviderId";
            public const string Acounts = "Acounts";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[Id] = vw_Users.ColumnNames.Id;
					ht[Name] = vw_Users.ColumnNames.Name;
					ht[Lname] = vw_Users.ColumnNames.Lname;
					ht[Email] = vw_Users.ColumnNames.Email;
					ht[Gender] = vw_Users.ColumnNames.Gender;
					ht[Bdate] = vw_Users.ColumnNames.Bdate;
					ht[Ocounts] = vw_Users.ColumnNames.Ocounts;
					ht[PasswordHash] = vw_Users.ColumnNames.PasswordHash;
					ht[Provider] = vw_Users.ColumnNames.Provider;
					ht[ProviderId] = vw_Users.ColumnNames.ProviderId;
					ht[Acounts] = vw_Users.ColumnNames.Acounts;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string Id = "s_Id";
            public const string Name = "s_Name";
            public const string Lname = "s_Lname";
            public const string Email = "s_Email";
            public const string Gender = "s_Gender";
            public const string Bdate = "s_Bdate";
            public const string Ocounts = "s_Ocounts";
            public const string PasswordHash = "s_PasswordHash";
            public const string Provider = "s_Provider";
            public const string ProviderId = "s_ProviderId";
            public const string Acounts = "s_Acounts";

		}
		#endregion	
		
		#region Properties
			public virtual int Id
	    {
			get
	        {
				return base.Getint(ColumnNames.Id);
			}
			set
	        {
				base.Setint(ColumnNames.Id, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual string Lname
	    {
			get
	        {
				return base.Getstring(ColumnNames.Lname);
			}
			set
	        {
				base.Setstring(ColumnNames.Lname, value);
			}
		}

		public virtual string Email
	    {
			get
	        {
				return base.Getstring(ColumnNames.Email);
			}
			set
	        {
				base.Setstring(ColumnNames.Email, value);
			}
		}

		public virtual bool Gender
	    {
			get
	        {
				return base.Getbool(ColumnNames.Gender);
			}
			set
	        {
				base.Setbool(ColumnNames.Gender, value);
			}
		}

		public virtual DateTime Bdate
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.Bdate);
			}
			set
	        {
				base.SetDateTime(ColumnNames.Bdate, value);
			}
		}

		public virtual int Ocounts
	    {
			get
	        {
				return base.Getint(ColumnNames.Ocounts);
			}
			set
	        {
				base.Setint(ColumnNames.Ocounts, value);
			}
		}

		public virtual string PasswordHash
	    {
			get
	        {
				return base.Getstring(ColumnNames.PasswordHash);
			}
			set
	        {
				base.Setstring(ColumnNames.PasswordHash, value);
			}
		}

		public virtual string Provider
	    {
			get
	        {
				return base.Getstring(ColumnNames.Provider);
			}
			set
	        {
				base.Setstring(ColumnNames.Provider, value);
			}
		}

		public virtual string ProviderId
	    {
			get
	        {
				return base.Getstring(ColumnNames.ProviderId);
			}
			set
	        {
				base.Setstring(ColumnNames.ProviderId, value);
			}
		}

		public virtual int Acounts
	    {
			get
	        {
				return base.Getint(ColumnNames.Acounts);
			}
			set
	        {
				base.Setint(ColumnNames.Acounts, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_Id
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Id) ? string.Empty : base.GetintAsString(ColumnNames.Id);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Id);
				else
					this.Id = base.SetintAsString(ColumnNames.Id, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_Lname
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Lname) ? string.Empty : base.GetstringAsString(ColumnNames.Lname);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Lname);
				else
					this.Lname = base.SetstringAsString(ColumnNames.Lname, value);
			}
		}

		public virtual string s_Email
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Email) ? string.Empty : base.GetstringAsString(ColumnNames.Email);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Email);
				else
					this.Email = base.SetstringAsString(ColumnNames.Email, value);
			}
		}

		public virtual string s_Gender
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Gender) ? string.Empty : base.GetboolAsString(ColumnNames.Gender);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Gender);
				else
					this.Gender = base.SetboolAsString(ColumnNames.Gender, value);
			}
		}

		public virtual string s_Bdate
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Bdate) ? string.Empty : base.GetDateTimeAsString(ColumnNames.Bdate);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Bdate);
				else
					this.Bdate = base.SetDateTimeAsString(ColumnNames.Bdate, value);
			}
		}

		public virtual string s_Ocounts
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Ocounts) ? string.Empty : base.GetintAsString(ColumnNames.Ocounts);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Ocounts);
				else
					this.Ocounts = base.SetintAsString(ColumnNames.Ocounts, value);
			}
		}

		public virtual string s_PasswordHash
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.PasswordHash) ? string.Empty : base.GetstringAsString(ColumnNames.PasswordHash);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.PasswordHash);
				else
					this.PasswordHash = base.SetstringAsString(ColumnNames.PasswordHash, value);
			}
		}

		public virtual string s_Provider
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Provider) ? string.Empty : base.GetstringAsString(ColumnNames.Provider);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Provider);
				else
					this.Provider = base.SetstringAsString(ColumnNames.Provider, value);
			}
		}

		public virtual string s_ProviderId
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ProviderId) ? string.Empty : base.GetstringAsString(ColumnNames.ProviderId);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ProviderId);
				else
					this.ProviderId = base.SetstringAsString(ColumnNames.ProviderId, value);
			}
		}

		public virtual string s_Acounts
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Acounts) ? string.Empty : base.GetintAsString(ColumnNames.Acounts);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Acounts);
				else
					this.Acounts = base.SetintAsString(ColumnNames.Acounts, value);
			}
		}


		#endregion			
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter Id
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Lname
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Lname, Parameters.Lname);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Email
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Email, Parameters.Email);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Gender
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Gender, Parameters.Gender);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Bdate
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Bdate, Parameters.Bdate);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Ocounts
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Ocounts, Parameters.Ocounts);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter PasswordHash
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.PasswordHash, Parameters.PasswordHash);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Provider
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Provider, Parameters.Provider);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ProviderId
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ProviderId, Parameters.ProviderId);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Acounts
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Acounts, Parameters.Acounts);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter Lname
		    {
				get
		        {
					if(_Lname_W == null)
	        	    {
						_Lname_W = TearOff.Lname;
					}
					return _Lname_W;
				}
			}

			public WhereParameter Email
		    {
				get
		        {
					if(_Email_W == null)
	        	    {
						_Email_W = TearOff.Email;
					}
					return _Email_W;
				}
			}

			public WhereParameter Gender
		    {
				get
		        {
					if(_Gender_W == null)
	        	    {
						_Gender_W = TearOff.Gender;
					}
					return _Gender_W;
				}
			}

			public WhereParameter Bdate
		    {
				get
		        {
					if(_Bdate_W == null)
	        	    {
						_Bdate_W = TearOff.Bdate;
					}
					return _Bdate_W;
				}
			}

			public WhereParameter Ocounts
		    {
				get
		        {
					if(_Ocounts_W == null)
	        	    {
						_Ocounts_W = TearOff.Ocounts;
					}
					return _Ocounts_W;
				}
			}

			public WhereParameter PasswordHash
		    {
				get
		        {
					if(_PasswordHash_W == null)
	        	    {
						_PasswordHash_W = TearOff.PasswordHash;
					}
					return _PasswordHash_W;
				}
			}

			public WhereParameter Provider
		    {
				get
		        {
					if(_Provider_W == null)
	        	    {
						_Provider_W = TearOff.Provider;
					}
					return _Provider_W;
				}
			}

			public WhereParameter ProviderId
		    {
				get
		        {
					if(_ProviderId_W == null)
	        	    {
						_ProviderId_W = TearOff.ProviderId;
					}
					return _ProviderId_W;
				}
			}

			public WhereParameter Acounts
		    {
				get
		        {
					if(_Acounts_W == null)
	        	    {
						_Acounts_W = TearOff.Acounts;
					}
					return _Acounts_W;
				}
			}

			private WhereParameter _Id_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _Lname_W = null;
			private WhereParameter _Email_W = null;
			private WhereParameter _Gender_W = null;
			private WhereParameter _Bdate_W = null;
			private WhereParameter _Ocounts_W = null;
			private WhereParameter _PasswordHash_W = null;
			private WhereParameter _Provider_W = null;
			private WhereParameter _ProviderId_W = null;
			private WhereParameter _Acounts_W = null;

			public void WhereClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_Lname_W = null;
				_Email_W = null;
				_Gender_W = null;
				_Bdate_W = null;
				_Ocounts_W = null;
				_PasswordHash_W = null;
				_Provider_W = null;
				_ProviderId_W = null;
				_Acounts_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter Id
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Id, Parameters.Id);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Lname
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Lname, Parameters.Lname);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Email
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Email, Parameters.Email);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Gender
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Gender, Parameters.Gender);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Bdate
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Bdate, Parameters.Bdate);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Ocounts
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Ocounts, Parameters.Ocounts);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter PasswordHash
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.PasswordHash, Parameters.PasswordHash);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Provider
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Provider, Parameters.Provider);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ProviderId
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ProviderId, Parameters.ProviderId);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Acounts
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Acounts, Parameters.Acounts);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter Id
		    {
				get
		        {
					if(_Id_W == null)
	        	    {
						_Id_W = TearOff.Id;
					}
					return _Id_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter Lname
		    {
				get
		        {
					if(_Lname_W == null)
	        	    {
						_Lname_W = TearOff.Lname;
					}
					return _Lname_W;
				}
			}

			public AggregateParameter Email
		    {
				get
		        {
					if(_Email_W == null)
	        	    {
						_Email_W = TearOff.Email;
					}
					return _Email_W;
				}
			}

			public AggregateParameter Gender
		    {
				get
		        {
					if(_Gender_W == null)
	        	    {
						_Gender_W = TearOff.Gender;
					}
					return _Gender_W;
				}
			}

			public AggregateParameter Bdate
		    {
				get
		        {
					if(_Bdate_W == null)
	        	    {
						_Bdate_W = TearOff.Bdate;
					}
					return _Bdate_W;
				}
			}

			public AggregateParameter Ocounts
		    {
				get
		        {
					if(_Ocounts_W == null)
	        	    {
						_Ocounts_W = TearOff.Ocounts;
					}
					return _Ocounts_W;
				}
			}

			public AggregateParameter PasswordHash
		    {
				get
		        {
					if(_PasswordHash_W == null)
	        	    {
						_PasswordHash_W = TearOff.PasswordHash;
					}
					return _PasswordHash_W;
				}
			}

			public AggregateParameter Provider
		    {
				get
		        {
					if(_Provider_W == null)
	        	    {
						_Provider_W = TearOff.Provider;
					}
					return _Provider_W;
				}
			}

			public AggregateParameter ProviderId
		    {
				get
		        {
					if(_ProviderId_W == null)
	        	    {
						_ProviderId_W = TearOff.ProviderId;
					}
					return _ProviderId_W;
				}
			}

			public AggregateParameter Acounts
		    {
				get
		        {
					if(_Acounts_W == null)
	        	    {
						_Acounts_W = TearOff.Acounts;
					}
					return _Acounts_W;
				}
			}

			private AggregateParameter _Id_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _Lname_W = null;
			private AggregateParameter _Email_W = null;
			private AggregateParameter _Gender_W = null;
			private AggregateParameter _Bdate_W = null;
			private AggregateParameter _Ocounts_W = null;
			private AggregateParameter _PasswordHash_W = null;
			private AggregateParameter _Provider_W = null;
			private AggregateParameter _ProviderId_W = null;
			private AggregateParameter _Acounts_W = null;

			public void AggregateClauseReset()
			{
				_Id_W = null;
				_Name_W = null;
				_Lname_W = null;
				_Email_W = null;
				_Gender_W = null;
				_Bdate_W = null;
				_Ocounts_W = null;
				_PasswordHash_W = null;
				_Provider_W = null;
				_ProviderId_W = null;
				_Acounts_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
			return null;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
			return null;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
			return null;
		}
	}
}
